// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateChannelRequestType.
const (
	N0 CreateChannelRequestType = 0
	N2 CreateChannelRequestType = 2
	N4 CreateChannelRequestType = 4
)

// Valid indicates whether the value is a known member of the CreateChannelRequestType enum.
func (e CreateChannelRequestType) Valid() bool {
	switch e {
	case N0:
		return true
	case N2:
		return true
	case N4:
		return true
	default:
		return false
	}
}

// Defines values for ErrorErrorCode.
const (
	ErrorErrorCodeAccessDenied          ErrorErrorCode = "access_denied"
	ErrorErrorCodeAlreadyBootstrapped   ErrorErrorCode = "already_bootstrapped"
	ErrorErrorCodeAuthorizationPending  ErrorErrorCode = "authorization_pending"
	ErrorErrorCodeBadRequest            ErrorErrorCode = "bad_request"
	ErrorErrorCodeChallengeInvalid      ErrorErrorCode = "challenge_invalid"
	ErrorErrorCodeConflict              ErrorErrorCode = "conflict"
	ErrorErrorCodeDeviceFlowUnavailable ErrorErrorCode = "device_flow_unavailable"
	ErrorErrorCodeExpiredToken          ErrorErrorCode = "expired_token"
	ErrorErrorCodeForbidden             ErrorErrorCode = "forbidden"
	ErrorErrorCodeInternalError         ErrorErrorCode = "internal_error"
	ErrorErrorCodeInviteInvalid         ErrorErrorCode = "invite_invalid"
	ErrorErrorCodeInviteRequired        ErrorErrorCode = "invite_required"
	ErrorErrorCodeMethodNotAllowed      ErrorErrorCode = "method_not_allowed"
	ErrorErrorCodeNotFound              ErrorErrorCode = "not_found"
	ErrorErrorCodeOauthEmailUnverified  ErrorErrorCode = "oauth_email_unverified"
	ErrorErrorCodeOauthProviderError    ErrorErrorCode = "oauth_provider_error"
	ErrorErrorCodeRateLimited           ErrorErrorCode = "rate_limited"
	ErrorErrorCodeRegistrationClosed    ErrorErrorCode = "registration_closed"
	ErrorErrorCodeResetUnavailable      ErrorErrorCode = "reset_unavailable"
	ErrorErrorCodeServiceUnavailable    ErrorErrorCode = "service_unavailable"
	ErrorErrorCodeSlowDown              ErrorErrorCode = "slow_down"
	ErrorErrorCodeUnauthorized          ErrorErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case ErrorErrorCodeAccessDenied:
		return true
	case ErrorErrorCodeAlreadyBootstrapped:
		return true
	case ErrorErrorCodeAuthorizationPending:
		return true
	case ErrorErrorCodeBadRequest:
		return true
	case ErrorErrorCodeChallengeInvalid:
		return true
	case ErrorErrorCodeConflict:
		return true
	case ErrorErrorCodeDeviceFlowUnavailable:
		return true
	case ErrorErrorCodeExpiredToken:
		return true
	case ErrorErrorCodeForbidden:
		return true
	case ErrorErrorCodeInternalError:
		return true
	case ErrorErrorCodeInviteInvalid:
		return true
	case ErrorErrorCodeInviteRequired:
		return true
	case ErrorErrorCodeMethodNotAllowed:
		return true
	case ErrorErrorCodeNotFound:
		return true
	case ErrorErrorCodeOauthEmailUnverified:
		return true
	case ErrorErrorCodeOauthProviderError:
		return true
	case ErrorErrorCodeRateLimited:
		return true
	case ErrorErrorCodeRegistrationClosed:
		return true
	case ErrorErrorCodeResetUnavailable:
		return true
	case ErrorErrorCodeServiceUnavailable:
		return true
	case ErrorErrorCodeSlowDown:
		return true
	case ErrorErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
	Starting HealthResponseStatus = "starting"
	Stopping HealthResponseStatus = "stopping"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	case Starting:
		return true
	case Stopping:
		return true
	default:
		return false
	}
}

// Defines values for Scope.
const (
	GuildsRead  Scope = "guilds.read"
	GuildsWrite Scope = "guilds.write"
	Identify    Scope = "identify"
)

// Valid indicates whether the value is a known member of the Scope enum.
func (e Scope) Valid() bool {
	switch e {
	case GuildsRead:
		return true
	case GuildsWrite:
		return true
	case Identify:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for OAuthProvider.
const (
	OAuthProviderGithub OAuthProvider = "github"
	OAuthProviderGoogle OAuthProvider = "google"
)

// Valid indicates whether the value is a known member of the OAuthProvider enum.
func (e OAuthProvider) Valid() bool {
	switch e {
	case OAuthProviderGithub:
		return true
	case OAuthProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for BeginOAuthParamsProvider.
const (
	BeginOAuthParamsProviderGithub BeginOAuthParamsProvider = "github"
	BeginOAuthParamsProviderGoogle BeginOAuthParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the BeginOAuthParamsProvider enum.
func (e BeginOAuthParamsProvider) Valid() bool {
	switch e {
	case BeginOAuthParamsProviderGithub:
		return true
	case BeginOAuthParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthCallbackParamsProvider.
const (
	OauthCallbackParamsProviderGithub OauthCallbackParamsProvider = "github"
	OauthCallbackParamsProviderGoogle OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case OauthCallbackParamsProviderGithub:
		return true
	case OauthCallbackParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for DecideDeviceAuthorizationFormdataBodyDecision.
const (
	Approve DecideDeviceAuthorizationFormdataBodyDecision = "approve"
	Deny    DecideDeviceAuthorizationFormdataBodyDecision = "deny"
)

// Valid indicates whether the value is a known member of the DecideDeviceAuthorizationFormdataBodyDecision enum.
func (e DecideDeviceAuthorizationFormdataBodyDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// ApiToken A scoped API token's metadata. Never includes the token value or its hash.
type ApiToken struct {
	CreatedAt time.Time `json:"created_at"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id Snowflake `json:"id"`

	// LastUsedAt Null until first use. Updated at most once every few minutes per token, not per request — see the listing endpoint's description.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// Name Human label chosen at mint time, so a token can be recognised later in order to revoke it.
	Name   string  `json:"name"`
	Scopes []Scope `json:"scopes"`
}

// BootstrapRequest The first administrator's account. The same fields and the same bounds as RegisterRequest, and they must stay the same: both create rows in one table under one set of constraints, so a value one accepts and the other rejects is a difference with nothing behind it.
type BootstrapRequest struct {
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
	Username    string              `json:"username"`
}

// Channel defines model for Channel.
type Channel struct {
	// Bitrate Voice channels only; null on every other type.
	Bitrate   *int      `json:"bitrate"`
	CreatedAt time.Time `json:"created_at"`

	// GuildId Null for a DM or group DM, which belong to no guild.
	GuildId *Snowflake `json:"guild_id"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id Snowflake `json:"id"`

	// LastMessageId Reserved until messages exist. Always null at this version.
	LastMessageId *Snowflake `json:"last_message_id"`
	Name          *string    `json:"name"`
	Nsfw          bool       `json:"nsfw"`

	// ParentId The category this channel sits under. Deleting a category sets this to null on its children rather than deleting them — losing a category must not lose the conversations in it.
	ParentId *Snowflake `json:"parent_id"`
	Position int        `json:"position"`
	Topic    *string    `json:"topic"`

	// Type `0` text, `1` DM, `2` voice, `3` group DM, `4` category, `5` announcement (reserved), `6` stage voice (reserved), `7` public matchmaking.
	//
	// Only `0`, `2` and `4` can be created through the guild-channel endpoint. The reserved values are part of the schema and stay there; voice is active v1 functionality, video and stage voice are the deferred-but-seamed parts.
	Type      int       `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`

	// UserLimit Voice channels only; null on every other type.
	UserLimit *int `json:"user_limit"`
}

// CreateChannelRequest defines model for CreateChannelRequest.
type CreateChannelRequest struct {
	Bitrate *int   `json:"bitrate,omitempty"`
	Name    string `json:"name"`
	Nsfw    *bool  `json:"nsfw,omitempty"`

	// ParentId A category **in this guild**. Verified rather than trusted: nesting under a category elsewhere would place this channel behind another guild's overwrites.
	ParentId *Snowflake `json:"parent_id,omitempty"`
	Position *int       `json:"position,omitempty"`
	Topic    *string    `json:"topic,omitempty"`

	// Type Text, voice, or category. See `Channel.type` for the values a guild cannot contain.
	Type      CreateChannelRequestType `json:"type"`
	UserLimit *int                     `json:"user_limit,omitempty"`
}

// CreateChannelRequestType Text, voice, or category. See `Channel.type` for the values a guild cannot contain.
type CreateChannelRequestType int

// CreateGuildRequest defines model for CreateGuildRequest.
type CreateGuildRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateInviteRequest Both fields are optional, and omitting either means "no limit".
type CreateInviteRequest struct {
	// ExpiresInSeconds Lifetime from now. Omit for an invite that never expires. Capped at a year — a longer-lived invite is almost always a mistake, and a permanent one is spelled by omitting the field rather than by a number nobody meant to type.
	ExpiresInSeconds *int `json:"expires_in_seconds,omitempty"`

	// MaxUses How many accounts may be created with this code. Omit for unlimited.
	MaxUses *int `json:"max_uses,omitempty"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	Color       *int   `json:"color,omitempty"`
	Hoist       *bool  `json:"hoist,omitempty"`
	Mentionable *bool  `json:"mentionable,omitempty"`
	Name        string `json:"name"`

	// Permissions Defaults to none. **Cannot exceed what the caller holds** — see the endpoint description for why that check is what stops `MANAGE_ROLES` from being every permission.
	Permissions *Permissions `json:"permissions,omitempty"`
}

// DeviceCodeRequest defines model for DeviceCodeRequest.
type DeviceCodeRequest struct {
	// DeviceId Stable per client install, and supplied here rather than at poll time because it is what the resulting session is scoped to — the browser that approves has no idea what it is. Rotation and reuse detection act within one device_id and never across them.
	DeviceId string `json:"device_id"`

	// DeviceName What this machine is called in the account's session list. Also shown on the verification page, so a person can see which device they are about to authorize. Bounded and escaped there; it is the client's own string, so a page presents it as one.
	DeviceName *string `json:"device_name,omitempty"`
}

// DeviceCodeResponse defines model for DeviceCodeResponse.
type DeviceCodeResponse struct {
	// DeviceCode The credential half. Trades for a token pair at `/auth/device/token` and must never be displayed, logged, or written anywhere a person could read it back.
	DeviceCode string `json:"device_code"`

	// ExpiresIn Seconds until both codes stop working. 1200 on this instance.
	ExpiresIn int `json:"expires_in"`

	// Interval Minimum seconds between polls. 5 on this instance. Read it rather than assuming it — see the endpoint description.
	Interval int `json:"interval"`

	// UserCode The half to show. Eight characters from a twenty-character alphabet — A-Z minus the vowels, so a draw does not spell anything, and minus `L`, which is misread as `1` or `I`; there are no digits at all, so `0` and `O` never meet. The dash is presentation only and the instance accepts the code with or without it, in any case.
	//
	// Display it verbatim. A client that re-cases or re-groups it is showing something other than what the instance issued.
	UserCode string `json:"user_code"`

	// VerificationUri Where to send the person. Absolute, and always on this instance's own origin — a client should check that before printing it, since it is a URL somebody is about to visit and type credentials into.
	VerificationUri string `json:"verification_uri"`
}

// DeviceTokenRequest defines model for DeviceTokenRequest.
type DeviceTokenRequest struct {
	// DeviceCode The `device_code` from `/auth/device/code`, verbatim.
	DeviceCode string `json:"device_code"`
}

// Error The envelope every non-2xx JSON response uses. Clients key off `code`, which is stable, never off `message`, which is human-readable and may change.
type Error struct {
	Error struct {
		// Code Stable, machine-readable error identifier.
		Code ErrorErrorCode `json:"code"`

		// Message Human-readable summary, safe to show a user.
		//
		// A 5xx message is generic — *except* where a handler has explicitly marked one as safe to send, which today is only the two `503`s above. Those say which feature is unconfigured, because "internal server error" would report an instance that is merely missing a setting as a broken one. What is never returned at any status is the underlying error: driver text, query fragments and hostnames are logged and stay there.
		Message string `json:"message"`

		// RequestId Correlation ID for this request, matching the `X-Request-Id` response header and the server-side log line.
		RequestId *string `json:"request_id,omitempty"`
	} `json:"error"`
}

// ErrorErrorCode Stable, machine-readable error identifier.
type ErrorErrorCode string

// Guild defines model for Guild.
type Guild struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description"`

	// IconHash Reserved. No upload endpoint exists yet, so this is always null.
	IconHash *string `json:"icon_hash"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id   Snowflake `json:"id"`
	Name string    `json:"name"`

	// OwnerId The account that bypasses every permission check within this guild (authority layer 2). Cannot be removed from the guild, and transferring it is not yet possible.
	OwnerId   Snowflake `json:"owner_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Detail Operator-facing explanation of a non-ok status. Omitted when status is `ok`.
	Detail *string `json:"detail,omitempty"`

	// Status Readiness state: `ok` is serving; `starting` is up but not finished booting (migrations may still be running); `stopping` is draining during shutdown; `degraded` is past startup but currently unable to reach the database.
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus Readiness state: `ok` is serving; `starting` is up but not finished booting (migrations may still be running); `stopping` is draining during shutdown; `degraded` is past startup but currently unable to reach the database.
type HealthResponseStatus string

// InstanceInvite defines model for InstanceInvite.
type InstanceInvite struct {
	// Code Sixteen characters from `BCDFGHJKMNPQRSTVWXYZ`, about 69 bits. Returned in full to an administrator, and stored in plaintext, which is a deliberate exception to this project's hash-everything rule: an invite exists to be handed to somebody, so it must be readable back, and what it authorizes is bounded — presenting one lets an account be created subject to every other rule registration enforces, and reaches no existing account or data.
	Code      string    `json:"code"`
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy Who issued it, or `null` when the instance operator did — the operator is not an account and has no id to record.
	CreatedBy *Snowflake `json:"created_by,omitempty"`

	// ExpiresAt When it stops working, or `null` if it never does.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// MaxUses How many uses it allows, or `null` for unlimited.
	MaxUses *int `json:"max_uses,omitempty"`

	// Uses How many accounts have been created with it.
	Uses int `json:"uses"`
}

// InstanceMeta The AGPL-3.0 section 13 source offer. Every field is present on every response; none is nullable.
type InstanceMeta struct {
	// License The SPDX identifier this instance's own code is distributed under. Not configurable — an operator may modify Norite and must then offer their modified source, but the terms they received it under are not theirs to restate.
	//
	//
	// Examples: AGPL-3.0-or-later
	License string `json:"license"`

	// SourceRevision The git revision the running binary was built from, or `unknown` for a build that was not stamped at link time.
	//
	//
	// Examples: v1.0.0, 9bb85f0, unknown
	SourceRevision string `json:"source_revision"`

	// SourceUrl Where this instance's Corresponding Source can be obtained. Defaults to the upstream repository; a modified instance must set it to its own.
	//
	//
	// Examples: https://github.com/Alexnex31/Norite
	SourceUrl string `json:"source_url"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// DeviceId Stable identifier for this installation — the daemon generates one per install and reuses it. Scopes the refresh-token family; see the endpoint description for why it is required.
	DeviceId string `json:"device_id"`

	// DeviceName Human label shown in a future session listing (M11). Optional.
	DeviceName *string             `json:"device_name,omitempty"`
	Email      openapi_types.Email `json:"email"`
	Password   string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// Member defines model for Member.
type Member struct {
	// Deaf Server-side deafen, set by a moderator. Distinct from the self-deafen a client sets on itself, which lives in voice state.
	Deaf bool `json:"deaf"`

	// GuildId A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	GuildId  Snowflake `json:"guild_id"`
	JoinedAt time.Time `json:"joined_at"`

	// Mute Server-side mute, set by a moderator. See `deaf`.
	Mute bool `json:"mute"`

	// Nickname A per-guild display name. Null means the account's own display name is used.
	Nickname *string `json:"nickname"`

	// Roles The roles this member holds, excluding `@everyone` — which every member holds and which appears in no grant. An empty array rather than null when there are none: a client that has to handle both writes the check once per field and forgets it somewhere.
	Roles []Snowflake `json:"roles"`

	// UserId A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	UserId Snowflake `json:"user_id"`
}

// MintApiTokenRequest defines model for MintApiTokenRequest.
type MintApiTokenRequest struct {
	Name string `json:"name"`

	// Scopes Must be non-empty and every entry must be recognised. A token with no scopes could do nothing, and an unrecognised scope is rejected rather than dropped.
	Scopes []Scope `json:"scopes"`
}

// MintedApiToken A newly-created API token, including its value. This is the only response that ever contains it.
//
// Spelled out in full rather than composed over `ApiToken` with `allOf`, which is what it used to do and which made it **unsatisfiable**: `allOf` branches are validated independently, so `ApiToken`'s `additionalProperties: false` rejected the very `value` the second branch required. No real response could match, and a validating client would have refused every successful mint — of a credential that cannot be recovered. Nothing caught it because the contract test compares the set of routes, not payloads. If a field is added to `ApiToken`, add it here too; the test named below fails until you do.
type MintedApiToken struct {
	CreatedAt time.Time `json:"created_at"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id Snowflake `json:"id"`

	// LastUsedAt Null on a token that has just been minted. See `ApiToken`.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// Name Human label chosen at mint time, so a token can be recognised later in order to revoke it.
	Name   string  `json:"name"`
	Scopes []Scope `json:"scopes"`

	// Value The credential itself, `nat_…`. Stored only as a SHA-256 hash and **not recoverable** — if it is lost, mint a new token and revoke this one. The `nat_` prefix exists so a leaked credential is identifiable on sight, by a human or a secret scanner.
	//
	//
	// Examples: nat_9pQ2xL7vD4mZ0kR8sT1yWbGhJcNfEuAiOoPdXrVtYnM
	Value string `json:"value"`
}

// OAuthCompleteRequest defines model for OAuthCompleteRequest.
type OAuthCompleteRequest struct {
	// SignupToken From the callback. Carries the provider-verified identity until a username is chosen; it is not a Bearer credential and authenticates nothing else.
	SignupToken string `json:"signup_token"`

	// Username Same rule as registration — see RegisterRequest.
	Username string `json:"username"`
}

// OAuthExchangeCode defines model for OAuthExchangeCode.
type OAuthExchangeCode struct {
	// Code Trade at `/auth/oauth/exchange` for a token pair.
	Code string `json:"code"`
}

// OAuthExchangeRequest defines model for OAuthExchangeRequest.
type OAuthExchangeRequest struct {
	// Code The one-time code from the callback. Single-use, and valid for minutes.
	Code string `json:"code"`

	// DeviceId Stable per client install. Scopes the refresh-token family, exactly as at login: rotation and reuse detection act within one device_id and never across them.
	DeviceId   string  `json:"device_id"`
	DeviceName *string `json:"device_name,omitempty"`

	// FlowVerifier The secret whose SHA-256 was sent as `flow_challenge` when this flow was started — the full `nof_`-prefixed string, not the bytes inside it. See `/auth/oauth/{provider}/authorize` for how the pair is constructed.
	//
	// Required: it is what makes the code redeemable by the client that began the sign-in and by nobody else, so a code obtained from a link somebody else crafted is worthless.
	//
	// A mismatch is answered exactly as an unknown or expired code, and spends the code either way.
	FlowVerifier string `json:"flow_verifier"`
}

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	// NewPassword Same rules as registration — length only, counted in characters.
	NewPassword string `json:"new_password"`

	// Token The token from the reset email. Single-use, and valid for one hour from when it was issued.
	Token string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Permissions A permission bitfield, as a **decimal string** rather than a number.
//
// The same decision snowflake ids take, for the same reason: this is a 63-bit value and JavaScript's number type is a float64, so anything above 2^53 loses precision silently in a browser. Nineteen bits are defined today, so the hazard is years away — which is exactly why the representation is fixed now, while changing it costs nothing.
//
// Bit positions, low to high: `VIEW_CHANNEL`, `SEND_MESSAGES`, `MANAGE_MESSAGES`, `MANAGE_CHANNELS`, `MANAGE_ROLES`, `KICK_MEMBERS`, `BAN_MEMBERS`, `CREATE_INVITE`, `MANAGE_GUILD`, `ADMINISTRATOR`, `CONNECT_VOICE`, `SPEAK_VOICE`, `VIDEO_VOICE`, `MUTE_MEMBERS`, `DEAFEN_MEMBERS`, `MENTION_EVERYONE`, `MANAGE_WEBHOOKS`, `MANAGE_EMOJIS`, `MODERATE_MEMBERS`.
//
// **The order is data, not documentation.** What the database stores is bit positions, so renumbering reassigns every permission every guild has already granted. `VIDEO_VOICE` is reserved and granted by nothing; it is listed because removing it would renumber the six bits above it.
//
// Examples: 3075, 0
type Permissions = string

// RecoveryCodes A fresh set of single-use recovery codes. Returned by confirmation and by regeneration, and shown exactly once — they are stored only as hashes, so nothing recoverable from the database can be presented as one (rule 8).
type RecoveryCodes struct {
	RecoveryCodes []string `json:"recovery_codes"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// ChallengeResponse **Reserved for M67a and ignored by every instance today.** Nothing emits a challenge yet, so sending this changes nothing and omitting it is correct.
	//
	// When M67a lands this carries the solved challenge — a proof-of-work solution, a hosted-captcha token, or whatever the mechanism chosen at build time produces. Opaque to this contract on purpose: the field is a carrier, and pinning its internal shape here would make swapping the mechanism a contract change across four clients, which is exactly what reserving it is meant to avoid.
	//
	// The ceiling is generous because a captcha provider's token is the largest plausible value and they are not small. It exists so an unbounded body cannot be posted at an unauthenticated endpoint, not because 4096 means anything.
	ChallengeResponse *string `json:"challenge_response,omitempty"`

	// DisplayName Defaults to the username when omitted.
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`

	// InviteCode Required while the instance is configured for invite-only registration, ignored while it is open. Sixteen characters drawn from `BCDFGHJKMNPQRSTVWXYZ` — no vowels, so a code is unlikely to spell anything, and no `L`, which is the third member of the `1`/`I`/`L` group that gets misread. Case, spaces and dashes are normalised away before lookup, so a code may be presented however it was pasted.
	// The maximum here is deliberately looser than the code's own length: what a code may contain is the instance's decision, and a bound that disagreed with it would refuse a valid code for the wrong reason.
	InviteCode *string `json:"invite_code,omitempty"`

	// Password Length is the only rule, counted in characters rather than bytes so a passphrase in a non-Latin script is not penalised. No composition requirements: they push people toward predictable substitutions while ruling out strong passphrases. The ceiling exists to bound hashing work.
	Password string `json:"password"`

	// Username Letters and digits in any script, plus `_`, `.` and `-`. An allow-list rather than a list of forbidden characters, so control codes, terminal escapes, bidirectional overrides and the various invisible spaces are all excluded without having to enumerate them. Emoji and other symbols are excluded too — `display_name` is the free-form field.
	// Length is counted in characters, not bytes, so a name in a non-Latin script is not penalised.
	// Normalised to NFKC before the uniqueness check, so two names that render identically cannot become two accounts: `ﬁnn` and `finn` are the same username. Unique case-insensitively. Normalisation happens before the length check, which a client submitting compatibility characters may notice — a 32-character name can normalise to something longer and be rejected.
	Username string `json:"username"`
}

// RegistrationChallenge **Reserved for M67a (registration anti-automation). Nothing produces one of these today.**
//
// The shape is reserved now rather than with the mechanism because rule 6 and rule 15 make it expensive once four clients generate from the current contract: adding a response state later is a coordinated regeneration across the CLI, the TUI, the GUI and the web SPA, where adding it now is three dozen lines nobody has to act on. The roadmap entry for M67a says the reservation lands with M12's contract work, and this is it.
//
// What is deliberately *not* fixed here is the mechanism. M67a chooses between proof-of-work, a hosted captcha, or both behind one interface at build time, and `parameters` is an open object so that choice does not become a contract change.
type RegistrationChallenge struct {
	// ExpiresAt When this challenge stops being accepted, so a client can offer a fresh one rather than submit a solution that will be refused. Optional: a stateless proof-of-work challenge need not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Mechanism Which challenge this instance is asking for, so a client knows what to render or compute.
	//
	// Deliberately not an enum. An enum would make adding a mechanism a breaking regeneration for every client, which is the cost this whole reservation exists to avoid — and a client that does not recognise the value should tell the person to use a client that does, not fail closed on a list this document froze years earlier.
	//
	//
	// Examples: proof_of_work, hcaptcha
	Mechanism string `json:"mechanism"`

	// Parameters Everything the client needs to produce a solution, in a shape the mechanism defines: a difficulty and a seed for proof-of-work, a site key for a hosted captcha.
	//
	// The one open object in this contract, and it is open on purpose rather than by omission — pinning it would tie the document to whichever mechanism was chosen first.
	Parameters map[string]interface{} `json:"parameters"`
}

// RevocationCounts What one call to the revocation primitive removed. Shared by `POST /auth/logout/all` and `DELETE /auth/2fa/totp`, which revoke exactly the same set — one schema for one server-side value, so that when M18 adds force-closed gateway connections and M101 adds E2E device trust, the count arrives in both places at once rather than in whichever was remembered.
type RevocationCounts struct {
	// ApiTokensRevoked API tokens revoked. Reported separately because it is the count a person needs to see to understand why a bot stopped.
	ApiTokensRevoked int64 `json:"api_tokens_revoked"`

	// DeviceAuthorizationsRevoked Device sign-ins that had been approved but not yet collected. Worth surfacing: somebody who approved a sign-in on a shared machine and then reached for this has just cancelled it, and nothing else would tell them.
	DeviceAuthorizationsRevoked int64 `json:"device_authorizations_revoked"`

	// OauthExchangeCodesRevoked Outstanding OAuth exchange codes cancelled. Usually zero.
	OauthExchangeCodesRevoked int64 `json:"oauth_exchange_codes_revoked"`

	// SessionsRevoked Session records revoked, across every device but this one.
	SessionsRevoked int64 `json:"sessions_revoked"`
}

// Role defines model for Role.
type Role struct {
	// Color 24-bit RGB. `0` means no colour, which renders as inherited rather than as black.
	Color     int       `json:"color"`
	CreatedAt time.Time `json:"created_at"`

	// GuildId A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	GuildId Snowflake `json:"guild_id"`

	// Hoist Whether members holding this role are shown in their own section of the member list.
	Hoist bool `json:"hoist"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id Snowflake `json:"id"`

	// IsDefault True for exactly one role per guild, `@everyone`. It is the floor every other role stacks on, it cannot be deleted or renamed, and every member holds it without appearing in any grant.
	IsDefault   bool   `json:"is_default"`
	Mentionable bool   `json:"mentionable"`
	Name        string `json:"name"`

	// Permissions A permission bitfield, as a **decimal string** rather than a number.
	//
	// The same decision snowflake ids take, for the same reason: this is a 63-bit value and JavaScript's number type is a float64, so anything above 2^53 loses precision silently in a browser. Nineteen bits are defined today, so the hazard is years away — which is exactly why the representation is fixed now, while changing it costs nothing.
	//
	// Bit positions, low to high: `VIEW_CHANNEL`, `SEND_MESSAGES`, `MANAGE_MESSAGES`, `MANAGE_CHANNELS`, `MANAGE_ROLES`, `KICK_MEMBERS`, `BAN_MEMBERS`, `CREATE_INVITE`, `MANAGE_GUILD`, `ADMINISTRATOR`, `CONNECT_VOICE`, `SPEAK_VOICE`, `VIDEO_VOICE`, `MUTE_MEMBERS`, `DEAFEN_MEMBERS`, `MENTION_EVERYONE`, `MANAGE_WEBHOOKS`, `MANAGE_EMOJIS`, `MODERATE_MEMBERS`.
	//
	// **The order is data, not documentation.** What the database stores is bit positions, so renumbering reassigns every permission every guild has already granted. `VIDEO_VOICE` is reserved and granted by nothing; it is listed because removing it would renumber the six bits above it.
	//
	//
	// Examples: 3075, 0
	Permissions Permissions `json:"permissions"`

	// Position Higher is higher in the hierarchy. `@everyone` is always 0. Not settable through these endpoints — reordering is a multi-row operation, and role hierarchy arrives with the permission-overwrite endpoints.
	Position  int       `json:"position"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Scope A capability an API token may be granted. Scopes only restrict a delegated credential below its owner's reach; they never grant. The vocabulary grows with the surface it guards.
//
// There is deliberately no scope for managing API tokens: minting, listing and revoking all require a logged-in user, because a credential that can create credentials can escalate itself.
//
// `guilds.read` and `guilds.write` are separate rather than one `guilds` scope, because the two have very different blast radii and the common bot wants only the first — a status bot that lists channels should not be one compromise away from deleting the guild. **Write does not imply read**: a scope bounds a delegated credential, and holding one is not a reason to be granted another, so a token that needs both asks for both.
type Scope string

// Session One device signed in to an account. A device, not a session record: the underlying rows rotate on every refresh, and `id` names whichever record is newest and live for that device right now.
type Session struct {
	// Current True for the device that made this request. Determined by the access token's `sid` claim resolved to its device, so it stays correct across the caller's own rotations.
	Current bool `json:"current"`

	// DeviceName What the client called this machine at sign-in, or empty if it did not say. **Client-supplied and untrusted** — sanitize before rendering it anywhere (CLAUDE.md rule 19). Sent as given rather than cleaned here, because cleaning it server-side would corrupt the value for every other consumer.
	DeviceName string `json:"device_name"`

	// ExpiresAt When the current record expires if the device never refreshes again.
	ExpiresAt time.Time `json:"expires_at"`

	// FirstSeen When this device first signed in, across the whole rotation family — **not** when it last rotated, which on an active device is at most fifteen minutes ago and would be useless.
	FirstSeen time.Time `json:"first_seen"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id Snowflake `json:"id"`

	// IpAddress Where this device was last seen from. Null for a session with no recorded address; present and explicitly null rather than omitted, so a caller reads the same keys either way.
	IpAddress  *string   `json:"ip_address"`
	LastUsedAt time.Time `json:"last_used_at"`
}

// Snowflake A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
//
// Examples: 7238829238972837423
type Snowflake = string

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessToken A JWT, presented as `Authorization: Bearer …`. Short-lived by design: revocation acts on the refresh session, so a stolen access token stays usable until it expires and the TTL is what bounds that window.
	AccessToken string `json:"access_token"`

	// ExpiresAt When the **access** token expires, not the refresh token. Clients refresh on this.
	ExpiresAt time.Time `json:"expires_at"`

	// RefreshToken An opaque `nrt_…` value, stored server-side only as a SHA-256 hash. Send it to `/auth/refresh` or `/auth/logout`; it is never a Bearer credential. Single-use — each refresh returns a new one, and presenting a spent one revokes the device's whole family.
	//
	//
	// Examples: nrt_kZ8m1H0dQ2s7pXv4b9RtLcYwJfN6aE3gUiOoPqSdTbA
	RefreshToken string             `json:"refresh_token"`
	TokenType    TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// TwoFactorChallenge The `202` a sign-in gets when the account owes a second factor. Not a credential: presenting one without a valid code produces exactly the refusal a wrong password does. What it removes is the need to send the password twice.
//
// `two_factor_required` is constant true and is present anyway, so a client reading a body without looking at the status still cannot mistake this for a token pair.
type TwoFactorChallenge struct {
	Challenge         string    `json:"challenge"`
	ExpiresAt         time.Time `json:"expires_at"`
	TwoFactorRequired bool      `json:"two_factor_required"`
}

// UpdateChannelRequest defines model for UpdateChannelRequest.
type UpdateChannelRequest struct {
	Bitrate *int `json:"bitrate,omitempty"`

	// ClearTopic Removes the topic. See `clear_description` on a guild for why this is a flag.
	ClearTopic *bool   `json:"clear_topic,omitempty"`
	Name       *string `json:"name,omitempty"`
	Nsfw       *bool   `json:"nsfw,omitempty"`
	Position   *int    `json:"position,omitempty"`
	Topic      *string `json:"topic,omitempty"`
	UserLimit  *int    `json:"user_limit,omitempty"`
}

// UpdateGuildRequest Every field optional; an absent one is left alone. At least conceptually a caller sends only what it means to change.
type UpdateGuildRequest struct {
	// ClearDescription Removes the description. A separate flag rather than a null `description`, because a JSON decoder cannot tell an explicit null from an absent field — and if absent meant "clear", every partial update would erase what it did not mention.
	ClearDescription *bool   `json:"clear_description,omitempty"`
	Description      *string `json:"description,omitempty"`
	Name             *string `json:"name,omitempty"`
}

// UpdateMemberRequest The permission required depends on which fields are present — see the endpoint description.
type UpdateMemberRequest struct {
	// ClearNickname Removes the nickname. See `clear_description` on a guild for why this is a flag.
	ClearNickname *bool   `json:"clear_nickname,omitempty"`
	Deaf          *bool   `json:"deaf,omitempty"`
	Mute          *bool   `json:"mute,omitempty"`
	Nickname      *string `json:"nickname,omitempty"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	Color       *int  `json:"color,omitempty"`
	Hoist       *bool `json:"hoist,omitempty"`
	Mentionable *bool `json:"mentionable,omitempty"`

	// Name Refused for `@everyone`.
	Name *string `json:"name,omitempty"`

	// Permissions Cannot exceed what the caller holds. Permitted on `@everyone`, unlike the name.
	Permissions *Permissions `json:"permissions,omitempty"`
}

// User An account. Never carries `password_hash` or any other credential material — this shape is built field-by-field from the database row rather than serialised from it, so a column added later cannot leak onto the wire by default.
type User struct {
	AvatarHash  *string   `json:"avatar_hash,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`

	// Email Unique, case-insensitively.
	Email openapi_types.Email `json:"email"`

	// EmailVerifiedAt Null while the address is unconfirmed. Set when a confirmation link is followed (M10), when a provider vouched for the address, or on creation for an account made by `/instance/bootstrap` or on an instance with no mail relay. An account with this null cannot sign in.
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`

	// Id A Snowflake ID as a decimal string. Always a string, never a JSON number — Snowflakes exceed 2^53, so numeric parsing silently loses precision (docs/adr/0003-snowflake-ids.md).
	//
	//
	// Examples: 7238829238972837423
	Id Snowflake `json:"id"`

	// RecoveryCodesRemaining How many unspent recovery codes the account has. Null rather than zero when there is no factor at all — zero would read as "you have run out" rather than "there is nothing to run out of".
	RecoveryCodesRemaining *int64 `json:"recovery_codes_remaining,omitempty"`

	// TwoFactorEnabled True only for a *confirmed* enrollment. An enrollment somebody started and abandoned is not a factor and must not read as one, or the account looks protected when it is not.
	TwoFactorEnabled *bool `json:"two_factor_enabled,omitempty"`

	// Username Unique, case-insensitively.
	Username string `json:"username"`
}

// OAuthProvider defines model for OAuthProvider.
type OAuthProvider string

// BadRequest The envelope every non-2xx JSON response uses. Clients key off `code`, which is stable, never off `message`, which is human-readable and may change.
type BadRequest = Error

// Forbidden The envelope every non-2xx JSON response uses. Clients key off `code`, which is stable, never off `message`, which is human-readable and may change.
type Forbidden = Error

// NotFound The envelope every non-2xx JSON response uses. Clients key off `code`, which is stable, never off `message`, which is human-readable and may change.
type NotFound = Error

// RateLimited The envelope every non-2xx JSON response uses. Clients key off `code`, which is stable, never off `message`, which is human-readable and may change.
type RateLimited = Error

// Unauthorized The envelope every non-2xx JSON response uses. Clients key off `code`, which is stable, never off `message`, which is human-readable and may change.
type Unauthorized = Error

// RegenerateRecoveryCodesJSONBody defines parameters for RegenerateRecoveryCodes.
type RegenerateRecoveryCodesJSONBody struct {
	Code string `json:"code"`
}

// DisableTwoFactorJSONBody defines parameters for DisableTwoFactor.
type DisableTwoFactorJSONBody struct {
	// Code An authenticator code or a recovery code.
	Code string `json:"code"`
}

// ConfirmTotpEnrollmentJSONBody defines parameters for ConfirmTotpEnrollment.
type ConfirmTotpEnrollmentJSONBody struct {
	Code string `json:"code"`
}

// VerifyTwoFactorJSONBody defines parameters for VerifyTwoFactor.
type VerifyTwoFactorJSONBody struct {
	// Challenge The continuation from the 202. Not a credential on its own.
	Challenge string `json:"challenge"`
	Code      string `json:"code"`
}

// BeginOAuthParams defines parameters for BeginOAuth.
type BeginOAuthParams struct {
	// FlowChallenge Base64url (unpadded) SHA-256 of the flow verifier. 43 characters.
	//
	// Required for every flow a client starts. Exactly one of `flow_challenge` and `device_token` must be present — see `device_token` for what the second one is and why it does not need this.
	FlowChallenge *string `form:"flow_challenge,omitempty" json:"flow_challenge,omitempty"`

	// ClientRedirectUri A loopback listener to return to instead of rendering the callback's page. `http` only, on a loopback IP literal, with an explicit port, and with no userinfo, query or fragment.
	//
	// Refused alongside `device_token`: a device flow ends on a page this instance renders, so there is no listener for it to be returned to.
	ClientRedirectUri *string `form:"client_redirect_uri,omitempty" json:"client_redirect_uri,omitempty"`

	// DeviceToken The continuation from this instance's own device-verification page, present exactly when somebody is finishing a device-code sign-in with a provider (`/device`). It names the authorization being completed, so the callback ends on that flow's approval step rather than on a code or a redirect.
	//
	// **Not a substitute for `flow_challenge`, and not a case of the binding becoming optional.** A challenge exists so that the code a flow produces is redeemable only by the client that began it — and a device flow produces no code at all. The credential the waiting client will redeem is its device code, which it has held since before the browser was involved. Somebody who stole this parameter and completed the flow in their own browser would be shown an approval page for their own provider account, authorizing a device they already control.
	//
	// Clients do not construct this value. It comes from a link on the verification page and is useless anywhere else.
	DeviceToken *string `form:"device_token,omitempty" json:"device_token,omitempty"`
}

// BeginOAuthParamsProvider defines parameters for BeginOAuth.
type BeginOAuthParamsProvider string

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Set by the provider when the user declined or it refused. Treated as an ordinary abandonment, not a fault.
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// RequestEmailVerificationJSONBody defines parameters for RequestEmailVerification.
type RequestEmailVerificationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// GetDevicePageParams defines parameters for GetDevicePage.
type GetDevicePageParams struct {
	// Code Prefills the field and does nothing else — no lookup, no state, no step skipped. A value that is not a well-formed user code is dropped rather than echoed back.
	//
	// This is deliberately not `verification_uri_complete`. That parameter completes the entry step from the URL, which turns a phished link into a single click; this one saves eight keystrokes somebody still has to look at before pressing Continue.
	Code *string `form:"code,omitempty" json:"code,omitempty"`
}

// SubmitDevicePageFormdataBody defines parameters for SubmitDevicePage.
type SubmitDevicePageFormdataBody struct {
	// UserCode Case, spaces and the grouping dash are all normalized away, so a person is not punished for typing what their phone keyboard offered.
	UserCode string `form:"user_code" json:"user_code"`
}

// ProveFactorOnDevicePageFormdataBody defines parameters for ProveFactorOnDevicePage.
type ProveFactorOnDevicePageFormdataBody struct {
	// Code An authenticator code or a recovery code.
	Code string `form:"code" json:"code"`

	// DeviceToken A continuation of its own type, distinct from the one the previous step carried and from the one the next step takes. It asserts that this browser has proved a password but not yet a factor — a state that is neither of the other two, and collapsing it into either would authorize before authentication had finished.
	DeviceToken string `form:"device_token" json:"device_token"`
}

// DecideDeviceAuthorizationFormdataBody defines parameters for DecideDeviceAuthorization.
type DecideDeviceAuthorizationFormdataBody struct {
	// Decision Anything other than `approve` denies, so a malformed submission fails closed. A denial is final: the waiting client is told on its next poll and the code cannot be reused.
	Decision DecideDeviceAuthorizationFormdataBodyDecision `form:"decision" json:"decision"`

	// DeviceToken The signed continuation from the sign-in step, which names both the authorization and the account.
	DeviceToken string `form:"device_token" json:"device_token"`
}

// DecideDeviceAuthorizationFormdataBodyDecision defines parameters for DecideDeviceAuthorization.
type DecideDeviceAuthorizationFormdataBodyDecision string

// SignInOnDevicePageFormdataBody defines parameters for SignInOnDevicePage.
type SignInOnDevicePageFormdataBody struct {
	// DeviceToken The signed continuation from the previous step. Carries which authorization is being worked on; asserts nothing about who is signing in, which is what the next one is for.
	DeviceToken string              `form:"device_token" json:"device_token"`
	Email       openapi_types.Email `form:"email" json:"email"`
	Password    string              `form:"password" json:"password"`
}

// ListGuildMembersParams defines parameters for ListGuildMembers.
type ListGuildMembersParams struct {
	// After Resume after this user id, exclusive. Omit for the first page.
	After *Snowflake `form:"after,omitempty" json:"after,omitempty"`

	// Limit Page size. Defaults to 50, and values above 100 are **clamped rather than refused** — a client asking for more than the ceiling is not making an error worth failing a request over, and returning the ceiling communicates it more clearly than a 400 it has to parse.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// RevokeInstanceInviteJSONBody defines parameters for RevokeInstanceInvite.
type RevokeInstanceInviteJSONBody struct {
	// Code The invite code. Case, spaces and dashes are normalised away before lookup.
	Code string `json:"code"`
}

// ContinueOAuthSignupParams defines parameters for ContinueOAuthSignup.
type ContinueOAuthSignupParams struct {
	// Token The signup continuation token from the email.
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// SubmitOAuthSignupFormdataBody defines parameters for SubmitOAuthSignup.
type SubmitOAuthSignupFormdataBody struct {
	SignupToken string `form:"signup_token" json:"signup_token"`
	Username    string `form:"username" json:"username"`
}

// GetResetPageParams defines parameters for GetResetPage.
type GetResetPageParams struct {
	// Token The reset token from the email. Absent or wrong, the form still renders and the submission is what fails — for the reason above.
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// SubmitResetPageFormdataBody defines parameters for SubmitResetPage.
type SubmitResetPageFormdataBody struct {
	Password string `form:"password" json:"password"`
	Token    string `form:"token" json:"token"`
}

// GetVerifyPageParams defines parameters for GetVerifyPage.
type GetVerifyPageParams struct {
	// Token The verification token, carried into the form. Absent renders the page with an empty field, which then fails on submit.
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// ConfirmEmailVerificationFormdataBody defines parameters for ConfirmEmailVerification.
type ConfirmEmailVerificationFormdataBody struct {
	Token string `form:"token" json:"token"`
}

// RegenerateRecoveryCodesJSONRequestBody defines body for RegenerateRecoveryCodes for application/json ContentType.
type RegenerateRecoveryCodesJSONRequestBody RegenerateRecoveryCodesJSONBody

// DisableTwoFactorJSONRequestBody defines body for DisableTwoFactor for application/json ContentType.
type DisableTwoFactorJSONRequestBody DisableTwoFactorJSONBody

// ConfirmTotpEnrollmentJSONRequestBody defines body for ConfirmTotpEnrollment for application/json ContentType.
type ConfirmTotpEnrollmentJSONRequestBody ConfirmTotpEnrollmentJSONBody

// VerifyTwoFactorJSONRequestBody defines body for VerifyTwoFactor for application/json ContentType.
type VerifyTwoFactorJSONRequestBody VerifyTwoFactorJSONBody

// StartDeviceAuthorizationJSONRequestBody defines body for StartDeviceAuthorization for application/json ContentType.
type StartDeviceAuthorizationJSONRequestBody = DeviceCodeRequest

// PollDeviceAuthorizationJSONRequestBody defines body for PollDeviceAuthorization for application/json ContentType.
type PollDeviceAuthorizationJSONRequestBody = DeviceTokenRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// CompleteOAuthSignupJSONRequestBody defines body for CompleteOAuthSignup for application/json ContentType.
type CompleteOAuthSignupJSONRequestBody = OAuthCompleteRequest

// ExchangeOAuthCodeJSONRequestBody defines body for ExchangeOAuthCode for application/json ContentType.
type ExchangeOAuthCodeJSONRequestBody = OAuthExchangeRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirmRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// MintApiTokenJSONRequestBody defines body for MintApiToken for application/json ContentType.
type MintApiTokenJSONRequestBody = MintApiTokenRequest

// RequestEmailVerificationJSONRequestBody defines body for RequestEmailVerification for application/json ContentType.
type RequestEmailVerificationJSONRequestBody RequestEmailVerificationJSONBody

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = UpdateChannelRequest

// SubmitDevicePageFormdataRequestBody defines body for SubmitDevicePage for application/x-www-form-urlencoded ContentType.
type SubmitDevicePageFormdataRequestBody SubmitDevicePageFormdataBody

// ProveFactorOnDevicePageFormdataRequestBody defines body for ProveFactorOnDevicePage for application/x-www-form-urlencoded ContentType.
type ProveFactorOnDevicePageFormdataRequestBody ProveFactorOnDevicePageFormdataBody

// DecideDeviceAuthorizationFormdataRequestBody defines body for DecideDeviceAuthorization for application/x-www-form-urlencoded ContentType.
type DecideDeviceAuthorizationFormdataRequestBody DecideDeviceAuthorizationFormdataBody

// SignInOnDevicePageFormdataRequestBody defines body for SignInOnDevicePage for application/x-www-form-urlencoded ContentType.
type SignInOnDevicePageFormdataRequestBody SignInOnDevicePageFormdataBody

// CreateGuildJSONRequestBody defines body for CreateGuild for application/json ContentType.
type CreateGuildJSONRequestBody = CreateGuildRequest

// UpdateGuildJSONRequestBody defines body for UpdateGuild for application/json ContentType.
type UpdateGuildJSONRequestBody = UpdateGuildRequest

// CreateGuildChannelJSONRequestBody defines body for CreateGuildChannel for application/json ContentType.
type CreateGuildChannelJSONRequestBody = CreateChannelRequest

// UpdateGuildMemberJSONRequestBody defines body for UpdateGuildMember for application/json ContentType.
type UpdateGuildMemberJSONRequestBody = UpdateMemberRequest

// CreateGuildRoleJSONRequestBody defines body for CreateGuildRole for application/json ContentType.
type CreateGuildRoleJSONRequestBody = CreateRoleRequest

// UpdateGuildRoleJSONRequestBody defines body for UpdateGuildRole for application/json ContentType.
type UpdateGuildRoleJSONRequestBody = UpdateRoleRequest

// BootstrapInstanceJSONRequestBody defines body for BootstrapInstance for application/json ContentType.
type BootstrapInstanceJSONRequestBody = BootstrapRequest

// CreateInstanceInviteJSONRequestBody defines body for CreateInstanceInvite for application/json ContentType.
type CreateInstanceInviteJSONRequestBody = CreateInviteRequest

// RevokeInstanceInviteJSONRequestBody defines body for RevokeInstanceInvite for application/json ContentType.
type RevokeInstanceInviteJSONRequestBody RevokeInstanceInviteJSONBody

// SubmitOAuthSignupFormdataRequestBody defines body for SubmitOAuthSignup for application/x-www-form-urlencoded ContentType.
type SubmitOAuthSignupFormdataRequestBody SubmitOAuthSignupFormdataBody

// SubmitResetPageFormdataRequestBody defines body for SubmitResetPage for application/x-www-form-urlencoded ContentType.
type SubmitResetPageFormdataRequestBody SubmitResetPageFormdataBody

// ConfirmEmailVerificationFormdataRequestBody defines body for ConfirmEmailVerification for application/x-www-form-urlencoded ContentType.
type ConfirmEmailVerificationFormdataRequestBody ConfirmEmailVerificationFormdataBody
