// SPDX-FileCopyrightText: 2026 Alexandre Duffez
// SPDX-License-Identifier: AGPL-3.0-or-later

// Package notices carries the third-party attribution text this binary must ship with.
//
// MIT, BSD and Apache-2.0 all require their notices to accompany a distributed binary, and a file sitting
// beside the binary in a release archive is easy to separate from it. Embedding is what makes the
// obligation survive somebody copying the executable somewhere on its own.
//
// The text is generated by "just notices" from "go version -m" on the built binary and committed; CI
// regenerates it and fails on a diff. It is deliberately not the same artifact as
// contracts/dependency-licenses.txt, which answers a policy question over all code rather than an
// attribution question over what ships — see docs/adr/0032-agpl-license.md.
//
// The file lives in this package rather than at the module root because go:embed cannot reach outside the
// directory of the package that declares it.
package notices

import _ "embed"

// Text is the full third-party notice document: every module the linker retained, with its complete
// license text and any NOTICE file.
//
//go:embed THIRD-PARTY-NOTICES.txt
var Text string
