#!/usr/bin/env bash
#
# Generate a binary's THIRD-PARTY-NOTICES.txt: every module the linker actually retained, with its full
# license text and any NOTICE file.
#
# This answers a different question from contracts/dependency-licenses.txt, and the two are deliberately
# not merged. The inventory asks "is every dependency's license on the allow-list" — a policy question,
# correctly answered over `./...` across all four modules. This asks "what must accompany this binary when
# it is distributed" — an attribution obligation MIT, BSD and Apache-2.0 all impose, and one that must not
# include code that never ships. Measured at the time of writing: `go-licenses report ./...` finds 75
# modules for backend, 14 of them testcontainers/docker/containerd, while the linked binary retains 29 and
# none of those. (The two tools also count slightly differently — go-licenses reports the import path it
# resolved a license at, so its per-binary figure is 30 paths for the same 29 modules.)
#
# The module set comes from `go version -m` on the built binary rather than from the module graph, because
# the linker is the only authority on what was retained. The SPDX identifier comes from `go-licenses
# report`, joined by longest prefix: go-licenses reports the import path it resolved a license at
# (golang.org/x/sys/unix) where `go version -m` reports the module (golang.org/x/sys).
#
# Usage: gen-third-party-notices.sh <module-dir> <main-pkg> <binary> <output>
set -euo pipefail

module_dir=$1; main_pkg=$2; binary=$3; out=$4

repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
modcache=$(go env GOMODCACHE)
first_party="github.com/Alexnex31/Norite"

# go-licenses' identifiers, one "importpath license" pair per line.
ids=$(cd "$repo/$module_dir" && GOWORK=off go-licenses report "$main_pkg" --ignore "$first_party" 2>/dev/null \
        | awk -F, 'NF>=3 {print $1, $NF}') \
  || { echo "gen-notices: $module_dir: go-licenses report failed; refusing to write a partial file" >&2; exit 1; }

# The module cache escapes an uppercase letter as '!' + its lowercase form.
escape() { printf '%s' "$1" | sed 's/\([A-Z]\)/!\L\1/g'; }

find_file() {
    local dir=$1; shift
    for name in "$@"; do
        if [ -f "$dir/$name" ]; then printf '%s' "$dir/$name"; return 0; fi
    done
    return 1
}

tmp=$(mktemp) && trap 'rm -f "$tmp"' EXIT

count=0
while read -r mod ver; do
    case "$mod" in "$first_party"*) continue ;; esac

    dir="$modcache/$(escape "$mod")@$ver"
    if [ ! -d "$dir" ]; then
        echo "gen-notices: $mod@$ver not in the module cache — run 'go mod download'" >&2
        exit 1
    fi

    lic=$(find_file "$dir" LICENSE LICENSE.txt LICENSE.md LICENCE COPYING COPYING.txt) \
      || { echo "gen-notices: no license file found for $mod@$ver in $dir" >&2; exit 1; }

    # Longest-prefix join: the identifier is reported against the import path, not the module path.
    id=$(awk -v m="$mod" 'index($1, m) == 1 && length($1) >= length(m) {
             if (length($1) > best) { best = length($1); v = $2 }
         } END { print (v == "" ? "UNKNOWN" : v) }' <<<"$ids")
    if [ "$id" = "UNKNOWN" ]; then
        echo "gen-notices: no license identifier for $mod — refusing to write a partial file" >&2
        exit 1
    fi

    {
        printf '================================================================================\n'
        printf '%s %s\n' "$mod" "$ver"
        printf 'SPDX-License-Identifier: %s\n' "$id"
        printf '================================================================================\n\n'
        cat "$lic"
        if notice=$(find_file "$dir" NOTICE NOTICE.txt NOTICE.md); then
            printf '\n---- NOTICE (propagated as Apache-2.0 section 4(d) requires) ----\n\n'
            cat "$notice"
        fi
        printf '\n\n'
    } >> "$tmp"
    count=$((count + 1))
done < <(go version -m "$repo/$binary" | awk '$1 == "dep" { print $2, $3 }' | LC_ALL=C sort)

{
    printf 'THIRD-PARTY NOTICES for %s\n' "$(basename "$binary")"
    printf '\n'
    printf 'Norite itself is licensed AGPL-3.0-or-later; see the LICENSE file at the repository root.\n'
    printf 'This file covers the third-party modules linked into this binary, and nothing else. It is\n'
    printf 'generated by `just notices` from `go version -m` on the built binary — the linker is the only\n'
    printf 'authority on what actually ships. Do not edit it by hand; CI regenerates it and fails on a diff.\n'
    printf '\n'
    printf '%d third-party modules.\n' "$count"
    printf '\n\n'
    cat "$tmp"
} > "$repo/$out"

echo "  $out ($count modules)"
