// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package db

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (id, user_id, name, token_hash, scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, scopes, created_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	ID        int64
	UserID    int64
	Name      string
	TokenHash []byte
	Scopes    []string
}

// Scoped API token queries.
//
// These are the long-lived, narrow-privilege credentials bots and local automation use, as opposed to the
// 15-minute access tokens a logged-in client holds. They are stored only as a SHA-256 hash, so the raw
// value is recoverable exactly once — in the response that created it.
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPITokenByHash = `-- name: GetActiveAPITokenByHash :one
SELECT t.id, t.user_id, t.name, t.token_hash, t.scopes, t.created_at, t.last_used_at, t.revoked_at FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND u.deleted_at IS NULL
`

// Runs on every request authenticated with an API token, which is why the hash column is indexed.
//
// One statement, not three: the owning account's liveness is joined in rather than fetched separately, and
// the revocation and soft-delete filters are applied here rather than in Go. An unusable token therefore
// returns no rows whatever the reason — which is also what the client is told, so nothing is lost by not
// distinguishing them.
func (q *Queries) GetActiveAPITokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getActiveAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, name, token_hash, scopes, created_at, last_used_at, revoked_at FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, name, token_hash, scopes, created_at, last_used_at, revoked_at
`

type RevokeAPITokenParams struct {
	ID     int64
	UserID int64
}

// Scoped by user_id as well as id: an actor may only revoke their own tokens, and enforcing that in the
// statement means a handler cannot forget to check ownership (CLAUDE.md rule 1).
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeAPIToken, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllAPITokensForUser = `-- name: RevokeAllAPITokensForUser :execrows
UPDATE api_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Every API token the account holds.
//
// Moved here from password_reset_tokens.sql at M11, for the reason RevokeAllSessionsForUser gives. The
// argument for revoking these alongside sessions moved with it, onto auth.revokeEverything.
func (q *Queries) RevokeAllAPITokensForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllAPITokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

// Records use, at most once every few minutes per token.
//
// Writing on every authenticated request would put a row update — and its WAL traffic, and its dead tuple
// for autovacuum — on the hottest read path in the API, to keep a timestamp accurate to the second that
// nothing needs to the second. The staleness window is the whole optimization: "last used" is for an
// operator auditing an account's tokens, and five minutes is well inside what that reader cares about.
//
// Still fire-and-forget: bookkeeping must never be able to fail an otherwise-valid request.
func (q *Queries) TouchAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
