// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :one
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, user_id, token_hash, sent_to, created_at, expires_at, consumed_at
`

// Spends a token, with single-use in the WHERE clause rather than in Go.
//
// Two confirms racing on the same link both reach this statement; the second finds consumed_at already set,
// matches zero rows, and is failed. Checking in the service and updating afterwards would let both win, and
// while a double verification is harmless in itself, the guarantee is what the address-change check below
// depends on.
func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, id int64) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationToken, id)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.SentTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one

INSERT INTO email_verification_tokens (id, user_id, token_hash, sent_to, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, sent_to, created_at, expires_at, consumed_at
`

type CreateEmailVerificationTokenParams struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	SentTo    string
	ExpiresAt pgtype.Timestamptz
}

// Email verification queries.
//
// The same shape as password_reset_tokens and deliberately so: two token tables with different rules about
// single-use or expiry would be two sets of guards to keep right, and the second one is always the one
// that gets it wrong.
func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.SentTo,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.SentTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :execrows
DELETE FROM email_verification_tokens
WHERE expires_at < now()
`

// Called by auth.RunSweeper. Non-partial index behind it — see 000010, and 000005 for why.
func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, user_id, token_hash, sent_to, created_at, expires_at, consumed_at FROM email_verification_tokens
WHERE token_hash = $1
`

// The confirm path's lookup. Expiry is checked here as well as in the consume below, so an expired token
// is refused before anything is written — the same two-step the reset path uses.
func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.SentTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const invalidateOutstandingVerificationTokens = `-- name: InvalidateOutstandingVerificationTokens :execrows
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Requesting verification again spends every older token for that account, so the newest link is the only
// one that works. Without it, each resend leaves another live token behind and the window a leaked mail is
// redeemable in becomes the union of all of them.
func (q *Queries) InvalidateOutstandingVerificationTokens(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateOutstandingVerificationTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND email = $2 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, display_name, avatar_hash, email_verified_at, created_at, updated_at, deleted_at
`

type MarkEmailVerifiedParams struct {
	ID    int64
	Email string
}

// Records that the address is confirmed.
//
// The WHERE guards against a race with an address change: the account's current email must still be the
// one the token was sent to. ConsumeEmailVerificationToken has already checked that the token is unspent,
// but the address can change between the two statements, and they run in one transaction precisely so this
// comparison is against a value that cannot move underneath it.
func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
