// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGuildMember = `-- name: AddGuildMember :one
INSERT INTO guild_members (guild_id, user_id, nickname)
VALUES ($1, $2, $3)
RETURNING guild_id, user_id, nickname, joined_at, deaf, mute
`

type AddGuildMemberParams struct {
	GuildID  int64
	UserID   int64
	Nickname *string
}

// ON CONFLICT DO NOTHING would make a second join silently succeed and return no row, which the caller
// cannot distinguish from a failed insert. Left to conflict instead, so the unique violation is the
// answer.
func (q *Queries) AddGuildMember(ctx context.Context, arg AddGuildMemberParams) (GuildMember, error) {
	row := q.db.QueryRow(ctx, addGuildMember, arg.GuildID, arg.UserID, arg.Nickname)
	var i GuildMember
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Deaf,
		&i.Mute,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, guild_id, type, parent_id, name, topic, position, nsfw, bitrate, user_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id, bitrate, user_limit, topic_search, created_at, updated_at
`

type CreateChannelParams struct {
	ID        int64
	GuildID   *int64
	Type      int16
	ParentID  *int64
	Name      *string
	Topic     *string
	Position  int32
	Nsfw      bool
	Bitrate   *int32
	UserLimit *int32
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.GuildID,
		arg.Type,
		arg.ParentID,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.Nsfw,
		arg.Bitrate,
		arg.UserLimit,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.Nsfw,
		&i.LastMessageID,
		&i.Bitrate,
		&i.UserLimit,
		&i.TopicSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGuild = `-- name: CreateGuild :one

INSERT INTO guilds (id, name, owner_id, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_id, icon_hash, description, system_channel_id, created_at, updated_at
`

type CreateGuildParams struct {
	ID          int64
	Name        string
	OwnerID     int64
	Description *string
}

// Guild, channel, role and membership queries (Milestone M12).
// The guild row. Its @everyone role and the owner's membership are written in the same transaction — see
// guilds.Service.Create, which is the only caller and does all three in one RunInTx.
func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.Description,
	)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconHash,
		&i.Description,
		&i.SystemChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, guild_id, name, color, permissions, position, hoist, mentionable, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at
`

type CreateRoleParams struct {
	ID          int64
	GuildID     int64
	Name        string
	Color       int32
	Permissions int64
	Position    int32
	Hoist       bool
	Mentionable bool
	IsDefault   bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.GuildID,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Position,
		arg.Hoist,
		arg.Mentionable,
		arg.IsDefault,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.Hoist,
		&i.Mentionable,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = $1 AND guild_id = $2
`

type DeleteChannelParams struct {
	ID      int64
	GuildID *int64
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGuild = `-- name: DeleteGuild :execrows
DELETE FROM guilds WHERE id = $1
`

// Everything below a guild is ON DELETE CASCADE, so this one statement takes the channels, roles,
// memberships, role grants, overwrites and audit entries with it.
//
// :execrows rather than :exec because the handler needs to tell "deleted" from "was not there" — not to
// report the difference, which would be the membership oracle authorize exists to close, but to avoid
// answering 204 for a guild that never existed.
func (q *Queries) DeleteGuild(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuild, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND guild_id = $2 AND NOT is_default
`

type DeleteRoleParams struct {
	ID      int64
	GuildID int64
}

// The is_default guard is in the WHERE rather than in Go, so a concurrent request cannot slip between a
// check and a delete. Same discipline as ConsumePasswordResetToken and RedeemInstanceInvite: a guard that
// lives in the statement cannot be raced, and one that lives in a Go `if` can.
//
// A guild without @everyone has no permission floor for resolution to start from, so this is not a policy
// nicety — it is the invariant guild creation establishes in its transaction.
func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id, bitrate, user_limit, topic_search, created_at, updated_at FROM channels WHERE id = $1
`

// By id alone, with no guild parameter, and that is deliberate rather than an oversight.
//
// PATCH /channels/{id} and DELETE /channels/{id} carry no guild in their path, so there is no guild id to
// scope by that did not come from the caller. The handler loads the channel, reads *its* guild_id, and
// authorizes against that — which is the only ordering rule 1 permits, since scoping the read by a
// caller-supplied guild would be trusting the value the check exists to verify.
func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.Nsfw,
		&i.LastMessageID,
		&i.Bitrate,
		&i.UserLimit,
		&i.TopicSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name, owner_id, icon_hash, description, system_channel_id, created_at, updated_at FROM guilds WHERE id = $1
`

func (q *Queries) GetGuild(ctx context.Context, id int64) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconHash,
		&i.Description,
		&i.SystemChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuildMember = `-- name: GetGuildMember :one
SELECT guild_id, user_id, nickname, joined_at, deaf, mute FROM guild_members WHERE guild_id = $1 AND user_id = $2
`

type GetGuildMemberParams struct {
	GuildID int64
	UserID  int64
}

func (q *Queries) GetGuildMember(ctx context.Context, arg GetGuildMemberParams) (GuildMember, error) {
	row := q.db.QueryRow(ctx, getGuildMember, arg.GuildID, arg.UserID)
	var i GuildMember
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Deaf,
		&i.Mute,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at FROM roles WHERE id = $1 AND guild_id = $2
`

type GetRoleParams struct {
	ID      int64
	GuildID int64
}

// Scoped by guild as well as by id, so a role id from another guild resolves to nothing rather than to
// somebody else's role. Rule 1: never trust a client-supplied ID without verifying it belongs to the
// actor's claimed context — enforced in the statement, not in a check a handler has to remember.
func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.GuildID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.Hoist,
		&i.Mentionable,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuildChannels = `-- name: ListGuildChannels :many
SELECT id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id,
       bitrate, user_limit, created_at, updated_at
FROM channels WHERE guild_id = $1 ORDER BY position, id
`

type ListGuildChannelsRow struct {
	ID            int64
	GuildID       *int64
	Type          int16
	ParentID      *int64
	Name          *string
	Topic         *string
	Position      int32
	Nsfw          bool
	LastMessageID *int64
	Bitrate       *int32
	UserLimit     *int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Columns enumerated rather than `SELECT *`, and topic_search is the reason.
//
// It is a generated tsvector that nothing in this codebase reads until M63's channel search, and pgx
// decodes it into a full pgtype.TSVector — a parsed lexeme list with positions and weights — on every row.
// Confirmed by probe: `SELECT *` scans fine, so this is not a correctness fix. It is that the channel list
// is one of rule 7's three named hot paths, and paying to transfer and parse a search index nobody reads,
// once per channel per listing, is exactly the over-fetching §15 asks not to ship.
//
// The three single-row channel queries keep `SELECT *`, deliberately. One row's tsvector costs nothing,
// and enumerating there too would give sqlc four near-identical row structs where one db.Channel does —
// four conversions to keep in step for no measurable gain. The cost this avoids is the one that multiplies
// by the number of channels, and that is this query alone.
func (q *Queries) ListGuildChannels(ctx context.Context, guildID *int64) ([]ListGuildChannelsRow, error) {
	rows, err := q.db.Query(ctx, listGuildChannels, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildChannelsRow{}
	for rows.Next() {
		var i ListGuildChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Type,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.Nsfw,
			&i.LastMessageID,
			&i.Bitrate,
			&i.UserLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildMembers = `-- name: ListGuildMembers :many
SELECT guild_id, user_id, nickname, joined_at, deaf, mute FROM guild_members
WHERE guild_id = $1 AND user_id > $2
ORDER BY user_id
LIMIT $3
`

type ListGuildMembersParams struct {
	GuildID int64
	UserID  int64
	Limit   int32
}

// Cursor pagination on user_id, never offset.
//
// §2 specifies cursor-only everywhere, and the member list is one of rule 7's named hot paths. An OFFSET
// makes page N cost N pages of scanning and shifts every row when somebody joins or leaves mid-read; a
// cursor costs one index descent regardless of depth and is stable under concurrent writes. The primary
// key (guild_id, user_id) serves it directly — measured as an Index Scan with no sort node on a
// 15,000-member guild.
func (q *Queries) ListGuildMembers(ctx context.Context, arg ListGuildMembersParams) ([]GuildMember, error) {
	rows, err := q.db.Query(ctx, listGuildMembers, arg.GuildID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuildMember{}
	for rows.Next() {
		var i GuildMember
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.Nickname,
			&i.JoinedAt,
			&i.Deaf,
			&i.Mute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildRoles = `-- name: ListGuildRoles :many
SELECT id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at FROM roles WHERE guild_id = $1 ORDER BY position, id
`

// Ordered by position, which the (guild_id, position) index serves.
func (q *Queries) ListGuildRoles(ctx context.Context, guildID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, listGuildRoles, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Color,
			&i.Permissions,
			&i.Position,
			&i.Hoist,
			&i.Mentionable,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRoleIDs = `-- name: ListMemberRoleIDs :many
SELECT guild_id, user_id, role_id
FROM guild_member_roles
WHERE guild_id = $1 AND user_id = ANY($2::bigint[])
`

type ListMemberRoleIDsParams struct {
	GuildID int64
	UserIds []int64
}

// The role ids held by each of a set of members, in one query rather than one per member.
//
// The member listing returns up to 100 members and each carries its roles, so the obvious shape — a query
// per member inside the loop — is the N+1 §15.2 names as the canonical risk. `= ANY($2)` resolves the
// whole page in one round trip, and the primary key's (guild_id, user_id) prefix serves it.
func (q *Queries) ListMemberRoleIDs(ctx context.Context, arg ListMemberRoleIDsParams) ([]GuildMemberRole, error) {
	rows, err := q.db.Query(ctx, listMemberRoleIDs, arg.GuildID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuildMemberRole{}
	for rows.Next() {
		var i GuildMemberRole
		if err := rows.Scan(&i.GuildID, &i.UserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGuildMember = `-- name: RemoveGuildMember :execrows
DELETE FROM guild_members WHERE guild_id = $1 AND user_id = $2
`

type RemoveGuildMemberParams struct {
	GuildID int64
	UserID  int64
}

func (q *Queries) RemoveGuildMember(ctx context.Context, arg RemoveGuildMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGuildMember, arg.GuildID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name       = COALESCE($1, name),
    topic      = CASE WHEN $2::boolean THEN NULL
                      ELSE COALESCE($3, topic) END,
    position   = COALESCE($4, position),
    nsfw       = COALESCE($5, nsfw),
    bitrate    = COALESCE($6, bitrate),
    user_limit = COALESCE($7, user_limit),
    updated_at = now()
WHERE id = $8 AND guild_id = $9
RETURNING id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id, bitrate, user_limit, topic_search, created_at, updated_at
`

type UpdateChannelParams struct {
	Name       *string
	ClearTopic bool
	Topic      *string
	Position   *int32
	Nsfw       *bool
	Bitrate    *int32
	UserLimit  *int32
	ID         int64
	GuildID    *int64
}

// Scoped by guild, because by the time this runs the handler has resolved the channel's own guild from
// GetChannel and authorized against it. Passing it back in is a second assertion that the row being
// written is the row that was checked.
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.ClearTopic,
		arg.Topic,
		arg.Position,
		arg.Nsfw,
		arg.Bitrate,
		arg.UserLimit,
		arg.ID,
		arg.GuildID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.Nsfw,
		&i.LastMessageID,
		&i.Bitrate,
		&i.UserLimit,
		&i.TopicSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuild = `-- name: UpdateGuild :one
UPDATE guilds
SET name        = COALESCE($1, name),
    description = CASE WHEN $2::boolean THEN NULL
                       ELSE COALESCE($3, description) END,
    updated_at  = now()
WHERE id = $4
RETURNING id, name, owner_id, icon_hash, description, system_channel_id, created_at, updated_at
`

type UpdateGuildParams struct {
	Name             *string
	ClearDescription bool
	Description      *string
	ID               int64
}

// Partial update through COALESCE, so a caller sends only the fields it means to change.
//
// The alternative — one statement per field, or a query builder — is what rule 3 forbids and what sqlc
// exists to avoid. NULL means "leave alone" rather than "set to NULL", which is why description clears
// through a separate flag: without it there would be no way to remove a description at all, since the
// value that means "clear this" and the value that means "do not touch this" would be the same.
func (q *Queries) UpdateGuild(ctx context.Context, arg UpdateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, updateGuild,
		arg.Name,
		arg.ClearDescription,
		arg.Description,
		arg.ID,
	)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconHash,
		&i.Description,
		&i.SystemChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuildMember = `-- name: UpdateGuildMember :one
UPDATE guild_members
SET nickname = CASE WHEN $1::boolean THEN NULL
                    ELSE COALESCE($2, nickname) END,
    deaf     = COALESCE($3, deaf),
    mute     = COALESCE($4, mute)
WHERE guild_id = $5 AND user_id = $6
RETURNING guild_id, user_id, nickname, joined_at, deaf, mute
`

type UpdateGuildMemberParams struct {
	ClearNickname bool
	Nickname      *string
	Deaf          *bool
	Mute          *bool
	GuildID       int64
	UserID        int64
}

func (q *Queries) UpdateGuildMember(ctx context.Context, arg UpdateGuildMemberParams) (GuildMember, error) {
	row := q.db.QueryRow(ctx, updateGuildMember,
		arg.ClearNickname,
		arg.Nickname,
		arg.Deaf,
		arg.Mute,
		arg.GuildID,
		arg.UserID,
	)
	var i GuildMember
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Deaf,
		&i.Mute,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name        = COALESCE($1, name),
    color       = COALESCE($2, color),
    permissions = COALESCE($3, permissions),
    hoist       = COALESCE($4, hoist),
    mentionable = COALESCE($5, mentionable),
    updated_at  = now()
WHERE id = $6 AND guild_id = $7
RETURNING id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        *string
	Color       *int32
	Permissions *int64
	Hoist       *bool
	Mentionable *bool
	ID          int64
	GuildID     int64
}

// Same COALESCE shape as UpdateGuild, and the same guild scoping as GetRole.
//
// position is not updatable here. Reordering roles is a multi-row swap and role *hierarchy* — who may
// manage whom — is M13's, so this milestone stores the column, orders by it, and does not let a single-row
// update reshuffle it.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Hoist,
		arg.Mentionable,
		arg.ID,
		arg.GuildID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.Hoist,
		&i.Mentionable,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeAuditLogEntry = `-- name: WriteAuditLogEntry :exec
INSERT INTO audit_log_entries (id, guild_id, actor_id, action, target_id, changes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type WriteAuditLogEntryParams struct {
	ID       int64
	GuildID  *int64
	ActorID  int64
	Action   string
	TargetID *int64
	Changes  []byte
}

// Rule 2, and it takes a querier rather than a pool for the reason the rule states: the entry is written
// in the same transaction as the mutation it records, so a mutation that commits without its entry is not
// a state this schema can reach.
//
// Nothing reads this until M14. `changes` is jsonb and M12 writes either NULL or a flat object of changed
// fields; M14 owns the diffing that produces a richer one.
func (q *Queries) WriteAuditLogEntry(ctx context.Context, arg WriteAuditLogEntryParams) error {
	_, err := q.db.Exec(ctx, writeAuditLogEntry,
		arg.ID,
		arg.GuildID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Changes,
	)
	return err
}
