// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGuildMember = `-- name: AddGuildMember :one
INSERT INTO guild_members (guild_id, user_id, nickname)
VALUES ($1, $2, $3)
RETURNING guild_id, user_id, nickname, joined_at, deaf, mute
`

type AddGuildMemberParams struct {
	GuildID  int64
	UserID   int64
	Nickname *string
}

// ON CONFLICT DO NOTHING would make a second join silently succeed and return no row, which the caller
// cannot distinguish from a failed insert. Left to conflict instead, so the unique violation is the
// answer.
func (q *Queries) AddGuildMember(ctx context.Context, arg AddGuildMemberParams) (GuildMember, error) {
	row := q.db.QueryRow(ctx, addGuildMember, arg.GuildID, arg.UserID, arg.Nickname)
	var i GuildMember
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Deaf,
		&i.Mute,
	)
	return i, err
}

const assignRoleToMember = `-- name: AssignRoleToMember :execrows

INSERT INTO guild_member_roles (guild_id, user_id, role_id)
SELECT gm.guild_id, gm.user_id, r.id
FROM guild_members gm
JOIN roles r ON r.guild_id = gm.guild_id
WHERE gm.guild_id = $1
  AND gm.user_id = $2
  AND r.id = $3
  AND NOT r.is_default
ON CONFLICT DO NOTHING
`

type AssignRoleToMemberParams struct {
	GuildID int64
	UserID  int64
	RoleID  int64
}

// Role assignment, role positions and permission overwrites (Milestone M13) follow. This separator is a
// lone comment line rather than prose, because sqlc attaches any comment block immediately above a query
// to that query's godoc — a section heading here becomes AssignRoleToMember's first documented sentence,
// and the Querier interface's.
//
// Give a member a role.
//
// # ON CONFLICT DO NOTHING, and why that became the right answer
//
// The first draft deliberately let the conflict surface, reasoning that ON CONFLICT DO NOTHING makes a
// repeat assignment return zero rows, indistinguishable from an insert that matched nothing — and those
// need different answers, an idempotent PUT succeeding against a 404. That is AddGuildMember's reasoning
// one table over, and it is sound where nothing has already established the preconditions.
//
// It is wrong here for a reason Postgres decides rather than this schema: a constraint violation aborts
// the surrounding transaction, so a caller cannot catch the conflict and carry on — and this statement
// runs inside the transaction that also writes the audit entry and reads the member back.
//
// What makes DO NOTHING safe is that the caller rules the other cases out first. AssignRole reads the role
// (404 if it is not in this guild) and the target's standing (404 if they are not a member) before
// reaching here, so zero rows can only mean the grant already exists — which is the PUT succeeding.
//
// The SELECT is what verifies both ids belong together before anything is written: the role must be in
// this guild, and the (guild, user) pair must be a real membership. Rule 1 in the statement rather than in
// a check a handler has to remember. The composite foreign key would refuse a non-member anyway, but it
// would do it as a constraint violation the caller has to reverse-engineer, and a 500 is not an answer.
//
// # Why NOT is_default
//
// @everyone is held by every member by virtue of membership and is never stored here — ListGuildMemberAuthority
// reads it through `is_default OR EXISTS(...)` precisely so that it does not have to be, and
// GetMemberHighestRolePosition's explanation rests on the same premise. Without this predicate the premise
// is merely a convention, and granting @everyone explicitly writes a row that permission resolution
// ignores, that the member's role list reports and nobody else's does, and that DeleteRole cannot remove
// because it refuses to delete the default role at all. Every other role-mutating statement here carries
// the same guard; this one was the exception until a review found it.
func (q *Queries) AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignRoleToMember, arg.GuildID, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyChannelOverwrites = `-- name: CopyChannelOverwrites :exec
INSERT INTO permission_overwrites (channel_id, target_type, target_id, allow, deny)
SELECT dest.id, po.target_type, po.target_id, po.allow, po.deny
FROM permission_overwrites po
JOIN channels src ON src.id = po.channel_id
JOIN channels dest ON dest.id = $1
WHERE po.channel_id = $2
  AND src.guild_id = $3::bigint
  AND dest.guild_id = $3::bigint
ON CONFLICT DO NOTHING
`

type CopyChannelOverwritesParams struct {
	ChannelID       int64
	SourceChannelID int64
	GuildID         int64
}

// Copy a category's overwrites onto a channel being created under it (Milestone M13).
//
// Inheritance is a copy at creation and not a lookup at resolution time, which is what Discord does: a
// channel does not follow its category's later permission changes, and "sync permissions with category" is
// a client re-copying through the overwrite endpoints rather than a flag anything stores. roles.Resolve
// therefore keeps reading exactly one channel's rows and never walks to a parent — resolution-time
// inheritance would put a second query on the check that runs before every mutation.
//
// Without this, a channel created inside a locked-down category is readable by everyone the moment it
// exists. That was unreachable while nothing could write an overwrite, which is why M12 does not do it.
//
// Not escalation-checked, deliberately: the copy replicates a configuration the guild already authored
// rather than authoring a new one, so refusing bits the creator does not hold would make inheritance fail
// exactly under the locked-down category it is most wanted under. What is checked is the creator's
// authority over the parent, in CreateChannel.
//
// # Both channels are scoped, not just the source
//
// The first draft constrained `guild_id` only on the join to the source channel and took the destination
// as a bare parameter, so it would happily copy one guild's overwrites onto another guild's channel —
// reproduced, four rows crossing. Today's only caller passes an id it minted a few lines earlier, which is
// what made it survive review of the statement in isolation; the sibling UpsertPermissionOverwrite claims
// exactly this property for itself in its own comment, and a rule that holds because of who happens to
// call it is not the rule that comment describes.
//
// It would also not have stayed harmless. target_id for a member overwrite is a global user id rather than
// a guild-scoped one, so a copied member row genuinely applies in the guild it landed in — applyOverwrites
// matches on user id — and DeleteOverwritesForTarget is guild-scoped, so nothing would ever clean it up.
func (q *Queries) CopyChannelOverwrites(ctx context.Context, arg CopyChannelOverwritesParams) error {
	_, err := q.db.Exec(ctx, copyChannelOverwrites, arg.ChannelID, arg.SourceChannelID, arg.GuildID)
	return err
}

const countChannelPermissionOverwrites = `-- name: CountChannelPermissionOverwrites :one
SELECT count(*) FROM permission_overwrites WHERE channel_id = $1
`

// How many overwrites a channel carries, for the creation ceiling.
//
// The ceiling exists for the reason CLAUDE.md settles for channels and roles: a list that cannot be
// paginated is bounded at creation instead. Overwrites are read whole — once per channel before every
// channel-scoped mutation, and once per guild on the channel listing — so an unbounded count is work on
// two hot paths, done on behalf of rows a caller wrote and nobody can see. target_id is polymorphic and
// cannot be a foreign key, so a fabricated one persists with nothing to clean it up.
//
// Served by the primary key's leading column.
func (q *Queries) CountChannelPermissionOverwrites(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelPermissionOverwrites, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuildChannels = `-- name: CountGuildChannels :one
SELECT count(*) FROM channels WHERE guild_id = $1
`

// How many channels a guild has, for the creation cap.
//
// Served by the leading column of channels_guild_id_position_idx: a bitmap index scan into the heap, 15
// buffers on a 50,000-channel instance, rather than a sequential scan of every channel on it. Not an
// *index-only* scan — the plan visits the heap for visibility — which is worth saying because the obvious
// shorthand for "an index serves this" is the wrong one here.
func (q *Queries) CountGuildChannels(ctx context.Context, guildID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildChannels, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuildRoles = `-- name: CountGuildRoles :one
SELECT count(*) FROM roles WHERE guild_id = $1
`

// How many roles a guild has, for the creation cap.
//
// A count, not NextRolePosition's max(position)+1 — deleting a role leaves a gap, so the highest position
// and the number of roles are different numbers and only one of them is the thing being capped.
//
// Same access path as the channel count above: bitmap index scan on roles_guild_id_position_idx, 10
// buffers on a 25,000-role instance.
func (q *Queries) CountGuildRoles(ctx context.Context, guildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildRoles, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuildsOwnedBy = `-- name: CountGuildsOwnedBy :one
SELECT count(*) FROM guilds WHERE owner_id = $1
`

// How many guilds an account owns, for the creation cap.
//
// Served by guilds_owner_id_idx, which 000015 added for the account-deletion FK check and which answers
// this for free.
func (q *Queries) CountGuildsOwnedBy(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildsOwnedBy, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, guild_id, type, parent_id, name, topic, position, nsfw, bitrate, user_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id, bitrate, user_limit, topic_search, created_at, updated_at
`

type CreateChannelParams struct {
	ID        int64
	GuildID   *int64
	Type      int16
	ParentID  *int64
	Name      *string
	Topic     *string
	Position  int32
	Nsfw      bool
	Bitrate   *int32
	UserLimit *int32
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.GuildID,
		arg.Type,
		arg.ParentID,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.Nsfw,
		arg.Bitrate,
		arg.UserLimit,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.Nsfw,
		&i.LastMessageID,
		&i.Bitrate,
		&i.UserLimit,
		&i.TopicSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGuild = `-- name: CreateGuild :one

INSERT INTO guilds (id, name, owner_id, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_id, icon_hash, description, system_channel_id, created_at, updated_at
`

type CreateGuildParams struct {
	ID          int64
	Name        string
	OwnerID     int64
	Description *string
}

// Guild, channel, role and membership queries (Milestone M12).
// The guild row. Its @everyone role and the owner's membership are written in the same transaction — see
// guilds.Service.Create, which is the only caller and does all three in one RunInTx.
func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.Description,
	)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconHash,
		&i.Description,
		&i.SystemChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, guild_id, name, color, permissions, position, hoist, mentionable, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at
`

type CreateRoleParams struct {
	ID          int64
	GuildID     int64
	Name        string
	Color       int32
	Permissions int64
	Position    int32
	Hoist       bool
	Mentionable bool
	IsDefault   bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.GuildID,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Position,
		arg.Hoist,
		arg.Mentionable,
		arg.IsDefault,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.Hoist,
		&i.Mentionable,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = $1 AND guild_id = $2
`

type DeleteChannelParams struct {
	ID      int64
	GuildID *int64
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGuild = `-- name: DeleteGuild :execrows
DELETE FROM guilds WHERE id = $1
`

// Everything below a guild is ON DELETE CASCADE, so this one statement takes the channels, roles,
// memberships, role grants, overwrites and audit entries with it.
//
// :execrows rather than :exec because the handler needs to tell "deleted" from "was not there" — not to
// report the difference, which would be the membership oracle authorize exists to close, but to avoid
// answering 204 for a guild that never existed.
func (q *Queries) DeleteGuild(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuild, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOverwritesForTarget = `-- name: DeleteOverwritesForTarget :exec
DELETE FROM permission_overwrites po
USING channels c
WHERE po.channel_id = c.id
  AND c.guild_id = $1::bigint
  AND po.target_type = $2
  AND po.target_id = $3
`

type DeleteOverwritesForTargetParams struct {
	GuildID    int64
	TargetType int16
	TargetID   int64
}

// Removes the permission overwrites that named a role or a member, across the whole guild.
//
// target_id is polymorphic — it names a role or a user depending on target_type — so it cannot be a
// foreign key, and nothing cascades. Without this, deleting a role leaves its overwrites behind forever on
// every channel that had one, and removing a member leaves theirs: rejoin the guild later and
// roles.applyOverwrites matches the member tier again and silently reapplies a deny nobody can see in the
// UI or explain from the audit log.
//
// Scoped through channels to the guild, so this cannot reach another guild's rows even though target_id
// alone would match them — a snowflake is unique in practice, but "in practice" is not the guarantee
// rule 1 asks for.
func (q *Queries) DeleteOverwritesForTarget(ctx context.Context, arg DeleteOverwritesForTargetParams) error {
	_, err := q.db.Exec(ctx, deleteOverwritesForTarget, arg.GuildID, arg.TargetType, arg.TargetID)
	return err
}

const deletePermissionOverwrite = `-- name: DeletePermissionOverwrite :execrows
DELETE FROM permission_overwrites po
USING channels c
WHERE po.channel_id = c.id
  AND c.guild_id = $1::bigint
  AND po.channel_id = $2
  AND po.target_type = $3
  AND po.target_id = $4
`

type DeletePermissionOverwriteParams struct {
	GuildID    int64
	ChannelID  int64
	TargetType int16
	TargetID   int64
}

// Remove an overwrite. Scoped through channels for UpsertPermissionOverwrite's reason.
func (q *Queries) DeletePermissionOverwrite(ctx context.Context, arg DeletePermissionOverwriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermissionOverwrite,
		arg.GuildID,
		arg.ChannelID,
		arg.TargetType,
		arg.TargetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND guild_id = $2 AND NOT is_default
`

type DeleteRoleParams struct {
	ID      int64
	GuildID int64
}

// The is_default guard is in the WHERE rather than in Go, so a concurrent request cannot slip between a
// check and a delete. Same discipline as ConsumePasswordResetToken and RedeemInstanceInvite: a guard that
// lives in the statement cannot be raced, and one that lives in a Go `if` can.
//
// A guild without @everyone has no permission floor for resolution to start from, so this is not a policy
// nicety — it is the invariant guild creation establishes in its transaction.
func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id, bitrate, user_limit, topic_search, created_at, updated_at FROM channels WHERE id = $1
`

// By id alone, with no guild parameter, and that is deliberate rather than an oversight.
//
// PATCH /channels/{id} and DELETE /channels/{id} carry no guild in their path, so there is no guild id to
// scope by that did not come from the caller. The handler loads the channel, reads *its* guild_id, and
// authorizes against that — which is the only ordering rule 1 permits, since scoping the read by a
// caller-supplied guild would be trusting the value the check exists to verify.
func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.Nsfw,
		&i.LastMessageID,
		&i.Bitrate,
		&i.UserLimit,
		&i.TopicSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name, owner_id, icon_hash, description, system_channel_id, created_at, updated_at FROM guilds WHERE id = $1
`

func (q *Queries) GetGuild(ctx context.Context, id int64) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconHash,
		&i.Description,
		&i.SystemChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuildMember = `-- name: GetGuildMember :one
SELECT guild_id, user_id, nickname, joined_at, deaf, mute FROM guild_members WHERE guild_id = $1 AND user_id = $2
`

type GetGuildMemberParams struct {
	GuildID int64
	UserID  int64
}

func (q *Queries) GetGuildMember(ctx context.Context, arg GetGuildMemberParams) (GuildMember, error) {
	row := q.db.QueryRow(ctx, getGuildMember, arg.GuildID, arg.UserID)
	var i GuildMember
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Deaf,
		&i.Mute,
	)
	return i, err
}

const getPermissionOverwrite = `-- name: GetPermissionOverwrite :one
SELECT po.channel_id, po.target_type, po.target_id, po.allow, po.deny
FROM permission_overwrites po
JOIN channels c ON c.id = po.channel_id
WHERE po.channel_id = $1
  AND po.target_type = $2
  AND po.target_id = $3
  AND c.guild_id = $4::bigint
`

type GetPermissionOverwriteParams struct {
	ChannelID  int64
	TargetType int16
	TargetID   int64
	GuildID    int64
}

// One overwrite, scoped to the guild through its channel.
//
// Read before every write and before every delete, because the escalation check covers the union of what
// the request changes: the bits the existing row allows or denies, or'd with the bits the new one does.
// Checking only the value being written leaves deletion checked by nothing at all — and deleting an
// overwrite that denies you something grants you that thing, which is a self-escalation on the endpoint
// whose whole subject is per-channel permissions.
func (q *Queries) GetPermissionOverwrite(ctx context.Context, arg GetPermissionOverwriteParams) (PermissionOverwrite, error) {
	row := q.db.QueryRow(ctx, getPermissionOverwrite,
		arg.ChannelID,
		arg.TargetType,
		arg.TargetID,
		arg.GuildID,
	)
	var i PermissionOverwrite
	err := row.Scan(
		&i.ChannelID,
		&i.TargetType,
		&i.TargetID,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at FROM roles WHERE id = $1 AND guild_id = $2
`

type GetRoleParams struct {
	ID      int64
	GuildID int64
}

// Scoped by guild as well as by id, so a role id from another guild resolves to nothing rather than to
// somebody else's role. Rule 1: never trust a client-supplied ID without verifying it belongs to the
// actor's claimed context — enforced in the statement, not in a check a handler has to remember.
func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.GuildID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.Hoist,
		&i.Mentionable,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuildChannels = `-- name: ListGuildChannels :many
SELECT id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id,
       bitrate, user_limit, created_at, updated_at
FROM channels WHERE guild_id = $1 ORDER BY position, id
`

type ListGuildChannelsRow struct {
	ID            int64
	GuildID       *int64
	Type          int16
	ParentID      *int64
	Name          *string
	Topic         *string
	Position      int32
	Nsfw          bool
	LastMessageID *int64
	Bitrate       *int32
	UserLimit     *int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Columns enumerated rather than `SELECT *`, and topic_search is the reason.
//
// It is a generated tsvector that nothing in this codebase reads until M63's channel search, and pgx
// decodes it into a full pgtype.TSVector — a parsed lexeme list with positions and weights — on every row.
// Confirmed by probe: `SELECT *` scans fine, so this is not a correctness fix. It is that the channel list
// is one of rule 7's three named hot paths, and paying to transfer and parse a search index nobody reads,
// once per channel per listing, is exactly the over-fetching §15 asks not to ship.
//
// The three single-row channel queries keep `SELECT *`, deliberately. One row's tsvector costs nothing,
// and enumerating there too would give sqlc four near-identical row structs where one db.Channel does —
// four conversions to keep in step for no measurable gain. The cost this avoids is the one that multiplies
// by the number of channels, and that is this query alone.
func (q *Queries) ListGuildChannels(ctx context.Context, guildID *int64) ([]ListGuildChannelsRow, error) {
	rows, err := q.db.Query(ctx, listGuildChannels, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildChannelsRow{}
	for rows.Next() {
		var i ListGuildChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Type,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.Nsfw,
			&i.LastMessageID,
			&i.Bitrate,
			&i.UserLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildMembers = `-- name: ListGuildMembers :many
SELECT guild_id, user_id, nickname, joined_at, deaf, mute FROM guild_members
WHERE guild_id = $1 AND user_id > $2
ORDER BY user_id
LIMIT $3
`

type ListGuildMembersParams struct {
	GuildID int64
	UserID  int64
	Limit   int32
}

// Cursor pagination on user_id, never offset.
//
// §2 specifies cursor-only everywhere, and the member list is one of rule 7's named hot paths. An OFFSET
// makes page N cost N pages of scanning and shifts every row when somebody joins or leaves mid-read; a
// cursor costs one index descent regardless of depth and is stable under concurrent writes. The primary
// key (guild_id, user_id) serves it directly — measured as an Index Scan with no sort node on a
// 15,000-member guild.
func (q *Queries) ListGuildMembers(ctx context.Context, arg ListGuildMembersParams) ([]GuildMember, error) {
	rows, err := q.db.Query(ctx, listGuildMembers, arg.GuildID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuildMember{}
	for rows.Next() {
		var i GuildMember
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.Nickname,
			&i.JoinedAt,
			&i.Deaf,
			&i.Mute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildRoles = `-- name: ListGuildRoles :many
SELECT id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at FROM roles WHERE guild_id = $1 ORDER BY position, id
`

// Ordered by position, which the (guild_id, position) index serves.
func (q *Queries) ListGuildRoles(ctx context.Context, guildID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, listGuildRoles, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Color,
			&i.Permissions,
			&i.Position,
			&i.Hoist,
			&i.Mentionable,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRoleIDs = `-- name: ListMemberRoleIDs :many
SELECT guild_id, user_id, role_id
FROM guild_member_roles
WHERE guild_id = $1 AND user_id = ANY($2::bigint[])
`

type ListMemberRoleIDsParams struct {
	GuildID int64
	UserIds []int64
}

// The role ids held by each of a set of members, in one query rather than one per member.
//
// The member listing returns up to 100 members and each carries its roles, so the obvious shape — a query
// per member inside the loop — is the N+1 §15.2 names as the canonical risk. `= ANY($2)` resolves the
// whole page in one round trip, and the primary key's (guild_id, user_id) prefix serves it.
func (q *Queries) ListMemberRoleIDs(ctx context.Context, arg ListMemberRoleIDsParams) ([]GuildMemberRole, error) {
	rows, err := q.db.Query(ctx, listMemberRoleIDs, arg.GuildID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuildMemberRole{}
	for rows.Next() {
		var i GuildMemberRole
		if err := rows.Scan(&i.GuildID, &i.UserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverwritesForTarget = `-- name: ListOverwritesForTarget :many
SELECT po.channel_id, po.target_type, po.target_id, po.allow, po.deny
FROM permission_overwrites po
JOIN channels c ON c.id = po.channel_id
WHERE c.guild_id = $1::bigint
  AND po.target_type = $2
  AND po.target_id = $3
`

type ListOverwritesForTargetParams struct {
	GuildID    int64
	TargetType int16
	TargetID   int64
}

// Every overwrite naming one role or member, across a guild, with the channel each sits on.
//
// Read before DeleteOverwritesForTarget deletes them, because removing an overwrite is a permission
// change however it is removed. DeleteOverwrite refuses a caller who does not hold the bits one row
// carries; deleting the role that row names reaches the same outcome for every channel at once, and was
// reaching it behind a guild-level permission check alone.
//
// Same access path as the delete it precedes: the ids restrict the scan and the channels join scopes it
// to the guild.
func (q *Queries) ListOverwritesForTarget(ctx context.Context, arg ListOverwritesForTargetParams) ([]PermissionOverwrite, error) {
	rows, err := q.db.Query(ctx, listOverwritesForTarget, arg.GuildID, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionOverwrite{}
	for rows.Next() {
		var i PermissionOverwrite
		if err := rows.Scan(
			&i.ChannelID,
			&i.TargetType,
			&i.TargetID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGuildRolePositions = `-- name: LockGuildRolePositions :exec
SELECT pg_advisory_xact_lock(1313033475, ($1::bigint & 2147483647)::int)
`

// Serializes role creation within one guild, for the whole of the calling transaction.
//
// NextRolePosition below is read and then acted on, which under READ COMMITTED — Postgres's default and
// this pool's, since RunInTx sets no isolation level — is a read-modify-write with a gap in it. Two
// concurrent creates both read the same max, neither sees the other's uncommitted INSERT, and both land on
// the same position. Migration 000015 deliberately declines a unique constraint on (guild_id, position),
// because reordering is a multi-row swap, so nothing downstream catches it.
//
// The consequence is not cosmetic: position is the hierarchy M13 enforces over, and two roles at the same
// position are neither above nor below each other.
//
// The read this serialises is no longer max(position)+1 — M13 places a new role at the bottom instead, so
// ShiftRolePositionsUp renumbers and CreateRole inserts at 1. The race is the same shape and the lock is
// the same answer: two concurrent creates would both renumber, both insert at 1, and leave the collision
// migration 000015 declines the unique constraint that would catch.
//
// An advisory lock rather than row locking, and the two-argument form so it lives in its own namespace:
// the first key is "NOR" plus a slot number (slot 1 is the migration lock, slot 2 the instance bootstrap,
// this is slot 3), the second is the guild. Two guilds whose low 31 bits collide serialize against each
// other unnecessarily and stay correct, which is the right direction for an operation that happens a
// handful of times in a guild's life.
func (q *Queries) LockGuildRolePositions(ctx context.Context, guildID int64) error {
	_, err := q.db.Exec(ctx, lockGuildRolePositions, guildID)
	return err
}

const removeGuildMember = `-- name: RemoveGuildMember :execrows
DELETE FROM guild_members WHERE guild_id = $1 AND user_id = $2
`

type RemoveGuildMemberParams struct {
	GuildID int64
	UserID  int64
}

func (q *Queries) RemoveGuildMember(ctx context.Context, arg RemoveGuildMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGuildMember, arg.GuildID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRolePosition = `-- name: SetRolePosition :execrows
UPDATE roles
SET position = $1, updated_at = now()
WHERE id = $2
  AND guild_id = $3
  AND NOT is_default
  AND $1::integer > 0
`

type SetRolePositionParams struct {
	Position int32
	ID       int64
	GuildID  int64
}

// One row of a reorder. The whole reorder is several of these in one transaction under the same advisory
// lock, because N separate requests would leave two roles sharing a position between them — and two roles
// at one position are neither above nor below each other, which dissolves the ordering every hierarchy
// check rests on.
//
// Two guards, and both are in the statement rather than in a check before it — the same discipline
// DeleteRole applies to the same role.
//
// `NOT is_default` refuses to move @everyone off 0. The position bound is the other half and is the one
// that is easy to leave out, because @everyone staying at 0 sounds like it already implies the floor is
// reserved. It does not: nothing stopped a *real* role being moved onto 0, or to a negative position below
// it. Both are corruptions rather than curiosities. A role sharing @everyone's position is neither above
// nor below it, which dissolves the strictly-greater comparison the whole hierarchy rests on; and
// GetMemberHighestRolePosition coalesces an absent maximum to 0, so a member whose only role sits at 0
// becomes indistinguishable from a member holding no roles at all — losing exactly the protection the
// position was granted to give them. A client sending zero-based positions is the ordinary way in, since
// role lists render 0-indexed.
//
// The *upper* bound lives in the service rather than here, because it derives from the configurable role
// ceiling: positions only ever grow through role creation, which shifts every role up by one, and the
// bound exists so that shift can never overflow `position`'s integer. A magic number in this file would be
// a policy constant in the wrong place, and the ceilings it follows from are already config.
func (q *Queries) SetRolePosition(ctx context.Context, arg SetRolePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRolePosition, arg.Position, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shiftRolePositionsUp = `-- name: ShiftRolePositionsUp :exec
UPDATE roles r
SET position = ranked.position, updated_at = now()
FROM (
    SELECT inner_r.id, (row_number() OVER (ORDER BY inner_r.position, inner_r.id) + 1)::integer AS position
    FROM roles inner_r
    WHERE inner_r.guild_id = $1 AND NOT inner_r.is_default
) ranked
WHERE r.id = ranked.id
  AND r.guild_id = $1
  AND r.position IS DISTINCT FROM ranked.position
`

// Make room at the bottom of the hierarchy for a new role (Milestone M13).
//
// A new role is created immediately above @everyone rather than above every existing role, which is what
// Discord does and what stops a non-owner creating a role they then cannot edit, delete, assign or
// reposition. That means everything else moves up one, and @everyone stays on the floor every layer-4
// resolution starts from.
//
// # Renumbering rather than shifting, so positions stay bounded by the ceiling
//
// The obvious implementation is `position = position + 1`, and it makes positions grow with the guild's
// *lifetime* creation count rather than with the roles it currently has. A guild that keeps one long-lived
// role and churns ten thousand others leaves that role near position 10,000 against a ceiling of 250 — so
// any service-side bound derived from the ceiling would reject a legitimate reorder of the guild's own
// current hierarchy, and nothing anywhere would bring the numbers back down.
//
// Renumbering from row_number() closes it: after every create, the live non-default roles occupy 2..N+1
// with position 1 free for the new one, so no position ever exceeds the role ceiling plus one. Relative
// order is preserved, which is the only property the hierarchy depends on — `ORDER BY position, id`
// matches ListGuildRoles, so two roles that tie today keep the order the listing already shows.
//
// At most 250 rows on a path that runs when somebody clicks "create role". It runs inside the same
// advisory lock CreateRole already takes, because two concurrent creates that both renumber and both
// insert at 1 would collide — and migration 000015 deliberately declines the unique constraint that would
// catch it.
// # The outer guild_id is not redundant, and an EXPLAIN is what says so
//
// `r.id = ranked.id` looks like it settles the outer scan: 253 primary keys, 253 lookups. The planner
// does not read it that way. It builds the ranked set, then *sequentially scans every role on the
// instance* and hash-joins — 25,254 rows read to update 253, because it has no restriction on `r` other
// than the join condition and a seq scan plus hash beats what it estimates the lookups to cost.
//
// Naming the guild on the outer relation gives it roles_guild_id_position_idx on both sides:
//
//	without   4.261 ms   Seq Scan on roles, 25,254 rows
//	with      1.879 ms   Bitmap Index Scan, this guild's roles only
//
// The ratio is the least interesting part. The seq-scan form's cost grows with the *instance's* role
// count while the indexed form grows with the guild's, so the gap widens for the life of the instance —
// the same shape 000015 measures three times over.
func (q *Queries) ShiftRolePositionsUp(ctx context.Context, guildID int64) error {
	_, err := q.db.Exec(ctx, shiftRolePositionsUp, guildID)
	return err
}

const unassignRoleFromMember = `-- name: UnassignRoleFromMember :execrows
DELETE FROM guild_member_roles
WHERE guild_id = $1 AND user_id = $2 AND role_id = $3
`

type UnassignRoleFromMemberParams struct {
	GuildID int64
	UserID  int64
	RoleID  int64
}

// Take a role away. Zero rows means the member did not hold it, which is an idempotent DELETE succeeding
// rather than an error — the caller has already established that the member exists, because the hierarchy
// check reads their standing first and GetMemberHighestRolePosition returns no row for a non-member.
//
// guild_id in the WHERE is not redundant with role_id: it scopes the delete to this guild's grant even
// though the pair could only ever appear together, which is the same belt-and-braces GetRole applies.
func (q *Queries) UnassignRoleFromMember(ctx context.Context, arg UnassignRoleFromMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, unassignRoleFromMember, arg.GuildID, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name       = COALESCE($1, name),
    topic      = CASE WHEN $2::boolean THEN NULL
                      ELSE COALESCE($3, topic) END,
    position   = COALESCE($4, position),
    nsfw       = COALESCE($5, nsfw),
    bitrate    = COALESCE($6, bitrate),
    user_limit = COALESCE($7, user_limit),
    updated_at = now()
WHERE id = $8 AND guild_id = $9
RETURNING id, guild_id, type, parent_id, name, topic, position, nsfw, last_message_id, bitrate, user_limit, topic_search, created_at, updated_at
`

type UpdateChannelParams struct {
	Name       *string
	ClearTopic bool
	Topic      *string
	Position   *int32
	Nsfw       *bool
	Bitrate    *int32
	UserLimit  *int32
	ID         int64
	GuildID    *int64
}

// Scoped by guild, because by the time this runs the handler has resolved the channel's own guild from
// GetChannel and authorized against it. Passing it back in is a second assertion that the row being
// written is the row that was checked.
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.ClearTopic,
		arg.Topic,
		arg.Position,
		arg.Nsfw,
		arg.Bitrate,
		arg.UserLimit,
		arg.ID,
		arg.GuildID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.Nsfw,
		&i.LastMessageID,
		&i.Bitrate,
		&i.UserLimit,
		&i.TopicSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuild = `-- name: UpdateGuild :one
UPDATE guilds
SET name        = COALESCE($1, name),
    description = CASE WHEN $2::boolean THEN NULL
                       ELSE COALESCE($3, description) END,
    updated_at  = now()
WHERE id = $4
RETURNING id, name, owner_id, icon_hash, description, system_channel_id, created_at, updated_at
`

type UpdateGuildParams struct {
	Name             *string
	ClearDescription bool
	Description      *string
	ID               int64
}

// Partial update through COALESCE, so a caller sends only the fields it means to change.
//
// The alternative — one statement per field, or a query builder — is what rule 3 forbids and what sqlc
// exists to avoid. NULL means "leave alone" rather than "set to NULL", which is why description clears
// through a separate flag: without it there would be no way to remove a description at all, since the
// value that means "clear this" and the value that means "do not touch this" would be the same.
func (q *Queries) UpdateGuild(ctx context.Context, arg UpdateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, updateGuild,
		arg.Name,
		arg.ClearDescription,
		arg.Description,
		arg.ID,
	)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconHash,
		&i.Description,
		&i.SystemChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuildMember = `-- name: UpdateGuildMember :one
UPDATE guild_members
SET nickname = CASE WHEN $1::boolean THEN NULL
                    ELSE COALESCE($2, nickname) END,
    deaf     = COALESCE($3, deaf),
    mute     = COALESCE($4, mute)
WHERE guild_id = $5 AND user_id = $6
RETURNING guild_id, user_id, nickname, joined_at, deaf, mute
`

type UpdateGuildMemberParams struct {
	ClearNickname bool
	Nickname      *string
	Deaf          *bool
	Mute          *bool
	GuildID       int64
	UserID        int64
}

func (q *Queries) UpdateGuildMember(ctx context.Context, arg UpdateGuildMemberParams) (GuildMember, error) {
	row := q.db.QueryRow(ctx, updateGuildMember,
		arg.ClearNickname,
		arg.Nickname,
		arg.Deaf,
		arg.Mute,
		arg.GuildID,
		arg.UserID,
	)
	var i GuildMember
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Deaf,
		&i.Mute,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name        = COALESCE($1, name),
    color       = COALESCE($2, color),
    permissions = COALESCE($3, permissions),
    hoist       = COALESCE($4, hoist),
    mentionable = COALESCE($5, mentionable),
    updated_at  = now()
WHERE id = $6 AND guild_id = $7
RETURNING id, guild_id, name, color, permissions, position, hoist, mentionable, is_default, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        *string
	Color       *int32
	Permissions *int64
	Hoist       *bool
	Mentionable *bool
	ID          int64
	GuildID     int64
}

// Same COALESCE shape as UpdateGuild, and the same guild scoping as GetRole.
//
// position is not updatable here. Reordering roles is a multi-row swap and role *hierarchy* — who may
// manage whom — is M13's, so this milestone stores the column, orders by it, and does not let a single-row
// update reshuffle it.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Hoist,
		arg.Mentionable,
		arg.ID,
		arg.GuildID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.Hoist,
		&i.Mentionable,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPermissionOverwrite = `-- name: UpsertPermissionOverwrite :one
INSERT INTO permission_overwrites (channel_id, target_type, target_id, allow, deny)
SELECT c.id, $1, $2, $3, $4
FROM channels c
WHERE c.id = $5 AND c.guild_id = $6::bigint
ON CONFLICT (channel_id, target_type, target_id)
DO UPDATE SET allow = EXCLUDED.allow, deny = EXCLUDED.deny
RETURNING channel_id, target_type, target_id, allow, deny
`

type UpsertPermissionOverwriteParams struct {
	TargetType int16
	TargetID   int64
	Allow      int64
	Deny       int64
	ChannelID  int64
	GuildID    int64
}

// Write an overwrite, creating or replacing.
//
// PUT rather than POST/PATCH on the wire, so the same statement has to serve both — ON CONFLICT on the
// primary key is what makes the endpoint idempotent. The row is selected from channels rather than
// supplied directly, so a channel in another guild inserts nothing and the caller sees pgx.ErrNoRows
// rather than writing an overwrite onto somebody else's channel (rule 1, in the statement).
func (q *Queries) UpsertPermissionOverwrite(ctx context.Context, arg UpsertPermissionOverwriteParams) (PermissionOverwrite, error) {
	row := q.db.QueryRow(ctx, upsertPermissionOverwrite,
		arg.TargetType,
		arg.TargetID,
		arg.Allow,
		arg.Deny,
		arg.ChannelID,
		arg.GuildID,
	)
	var i PermissionOverwrite
	err := row.Scan(
		&i.ChannelID,
		&i.TargetType,
		&i.TargetID,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}

const writeAuditLogEntry = `-- name: WriteAuditLogEntry :exec
INSERT INTO audit_log_entries (id, guild_id, actor_id, action, target_id, changes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type WriteAuditLogEntryParams struct {
	ID       int64
	GuildID  *int64
	ActorID  int64
	Action   string
	TargetID *int64
	Changes  []byte
}

// Rule 2, and it takes a querier rather than a pool for the reason the rule states: the entry is written
// in the same transaction as the mutation it records, so a mutation that commits without its entry is not
// a state this schema can reach.
//
// Nothing reads this until M14. `changes` is jsonb and M12 writes either NULL or a flat object of changed
// fields; M14 owns the diffing that produces a richer one.
func (q *Queries) WriteAuditLogEntry(ctx context.Context, arg WriteAuditLogEntryParams) error {
	_, err := q.db.Exec(ctx, writeAuditLogEntry,
		arg.ID,
		arg.GuildID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Changes,
	)
	return err
}
