// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance.sql

package db

import (
	"context"
)

const countInstanceAdmins = `-- name: CountInstanceAdmins :one

SELECT count(*) FROM instance_admins
`

// Instance-administration queries.
//
// The Instance Admin tier, which is instance-wide and sits outside roles.Resolve entirely (ADR 0013).
// M10 creates the first row and reads it; M71 adds granting, revoking, and the last-admin safety rail.
// The bootstrap guard, and the reason it is a count rather than an existence check.
//
// POST /instance/bootstrap is authorized by an operator token, which is minted from the instance signing
// key by anyone holding the config file. That is the right authority for creating the *first* admin and
// the wrong one for creating a second — an operator token replayed later must not be able to add an
// account to this table quietly. So the endpoint refuses unless this answers 0, which makes bootstrap
// self-disabling rather than needing a flag somewhere that says whether it already ran.
//
// Read inside the same transaction as the insert, so two simultaneous bootstraps cannot both see zero.
func (q *Queries) CountInstanceAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstanceAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstanceAdmin = `-- name: CreateInstanceAdmin :one
INSERT INTO instance_admins (user_id, granted_by)
VALUES ($1, $2)
RETURNING user_id, granted_by, granted_at
`

type CreateInstanceAdminParams struct {
	UserID    int64
	GrantedBy *int64
}

// granted_by is NULL for the bootstrap admin: nobody in this table granted it. See 000008.
func (q *Queries) CreateInstanceAdmin(ctx context.Context, arg CreateInstanceAdminParams) (InstanceAdmin, error) {
	row := q.db.QueryRow(ctx, createInstanceAdmin, arg.UserID, arg.GrantedBy)
	var i InstanceAdmin
	err := row.Scan(&i.UserID, &i.GrantedBy, &i.GrantedAt)
	return i, err
}

const isInstanceAdmin = `-- name: IsInstanceAdmin :one
SELECT EXISTS (
  SELECT 1 FROM instance_admins a
  JOIN users u ON u.id = a.user_id
  WHERE a.user_id = $1 AND u.deleted_at IS NULL
) AS is_admin
`

// The tier check, on every request to an instance-administration endpoint.
//
// Joined against users for liveness, the same shape and the same reasoning as GetActiveAPITokenByHash
// and GetOAuthIdentity: a soft-deleted account keeps its rows so its authored content still renders as
// "Deleted User", and this row is one of them. Without the join, deleting an admin's account would leave
// their tier intact and usable by any credential still outstanding on it.
func (q *Queries) IsInstanceAdmin(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isInstanceAdmin, userID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}
