// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGuildsJoinedBy = `-- name: CountGuildsJoinedBy :one
SELECT count(*) FROM guild_members WHERE user_id = $1
`

// How many guilds an account is in, owned ones included, for the joined ceiling (M20a). Counted under
// LockAccountOwnership; guild_members_user_id_idx serves it.
func (q *Queries) CountGuildsJoinedBy(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildsJoinedBy, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveGuildInvites = `-- name: CountLiveGuildInvites :one
SELECT count(*) FROM invites
WHERE guild_id = $1
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR uses < max_uses)
`

// How many live invites a guild has, for the creation ceiling. invites_guild_id_idx serves it.
func (q *Queries) CountLiveGuildInvites(ctx context.Context, guildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveGuildInvites, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuildInvite = `-- name: CreateGuildInvite :one

INSERT INTO invites (id, code, guild_id, channel_id, inviter_id, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5, $6::integer, $7::timestamptz)
RETURNING id, code, guild_id, channel_id, inviter_id, max_uses, uses, expires_at, created_at
`

type CreateGuildInviteParams struct {
	ID        int64
	Code      string
	GuildID   int64
	ChannelID int64
	InviterID int64
	MaxUses   *int32
	ExpiresAt pgtype.Timestamptz
}

// Guild invites (Milestone M20a).
//
// "Live" means not expired and not used up, and every statement that answers for a code asks both. The
// redemption that spends an invite's last use deletes it and the sweep removes expired ones, but neither
// is what makes a dead code answer as an unknown one: a deletion that fails or a sweep that has not run
// must not turn tidiness into a disclosure.
func (q *Queries) CreateGuildInvite(ctx context.Context, arg CreateGuildInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createGuildInvite,
		arg.ID,
		arg.Code,
		arg.GuildID,
		arg.ChannelID,
		arg.InviterID,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GuildID,
		&i.ChannelID,
		&i.InviterID,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredGuildInvites = `-- name: DeleteExpiredGuildInvites :execrows
DELETE FROM invites WHERE expires_at < now()
`

// The sweep (auth.SweepExpired), served by invites_expires_at_idx.
func (q *Queries) DeleteExpiredGuildInvites(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredGuildInvites)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGuildInvite = `-- name: DeleteGuildInvite :execrows
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteGuildInvite(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuildInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGuildInvitePreview = `-- name: GetGuildInvitePreview :one
SELECT
  i.code,
  i.expires_at,
  g.id          AS guild_id,
  g.name        AS guild_name,
  g.description AS guild_description,
  g.icon_hash   AS guild_icon_hash,
  c.id          AS channel_id,
  c.name        AS channel_name,
  i.inviter_id,
  u.username     AS inviter_username,
  u.display_name AS inviter_display_name
FROM invites i
JOIN guilds g   ON g.id = i.guild_id
JOIN channels c ON c.id = i.channel_id
LEFT JOIN users u ON u.id = i.inviter_id AND u.deleted_at IS NULL
WHERE i.code = $1
  AND (i.expires_at IS NULL OR i.expires_at > now())
  AND (i.max_uses IS NULL OR i.uses < i.max_uses)
`

type GetGuildInvitePreviewRow struct {
	Code               string
	ExpiresAt          pgtype.Timestamptz
	GuildID            int64
	GuildName          string
	GuildDescription   *string
	GuildIconHash      *string
	ChannelID          int64
	ChannelName        *string
	InviterID          int64
	InviterUsername    *string
	InviterDisplayName *string
}

// What a preview shows: where a live code leads, and who issued it.
//
// Every join is inner except the inviter's, so a code whose guild or channel is mid-deletion answers as an
// unknown one. Nothing here is gated on the caller beyond being signed in, deliberately: an invite is the
// guild's own decision to show itself to whoever holds the code, and the preview is how the person given
// it decides whether to use it.
func (q *Queries) GetGuildInvitePreview(ctx context.Context, code string) (GetGuildInvitePreviewRow, error) {
	row := q.db.QueryRow(ctx, getGuildInvitePreview, code)
	var i GetGuildInvitePreviewRow
	err := row.Scan(
		&i.Code,
		&i.ExpiresAt,
		&i.GuildID,
		&i.GuildName,
		&i.GuildDescription,
		&i.GuildIconHash,
		&i.ChannelID,
		&i.ChannelName,
		&i.InviterID,
		&i.InviterUsername,
		&i.InviterDisplayName,
	)
	return i, err
}

const getLiveGuildInvite = `-- name: GetLiveGuildInvite :one
SELECT id, code, guild_id, channel_id, inviter_id, max_uses, uses, expires_at, created_at FROM invites
WHERE code = $1
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR uses < max_uses)
`

// A live invite by its code: what revoking reads before deciding who may.
func (q *Queries) GetLiveGuildInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getLiveGuildInvite, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GuildID,
		&i.ChannelID,
		&i.InviterID,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGuildInvites = `-- name: ListGuildInvites :many
SELECT i.id, i.code, i.guild_id, i.channel_id, i.inviter_id, i.max_uses, i.uses, i.expires_at, i.created_at, u.username AS inviter_username, u.display_name AS inviter_display_name
FROM invites i
LEFT JOIN users u ON u.id = i.inviter_id AND u.deleted_at IS NULL
WHERE i.guild_id = $1
  AND (i.expires_at IS NULL OR i.expires_at > now())
  AND (i.max_uses IS NULL OR i.uses < i.max_uses)
ORDER BY i.id DESC
`

type ListGuildInvitesRow struct {
	Invite             Invite
	InviterUsername    *string
	InviterDisplayName *string
}

// A guild's live invites with each inviter's name, newest first. Unpaginated, like the channel and role
// lists, and bounded the same way: at creation, by [limits].invites_per_guild. The inviter is joined by
// primary key and dropped for a deleted account, as a message's author is (M20a).
func (q *Queries) ListGuildInvites(ctx context.Context, guildID int64) ([]ListGuildInvitesRow, error) {
	rows, err := q.db.Query(ctx, listGuildInvites, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildInvitesRow{}
	for rows.Next() {
		var i ListGuildInvitesRow
		if err := rows.Scan(
			&i.Invite.ID,
			&i.Invite.Code,
			&i.Invite.GuildID,
			&i.Invite.ChannelID,
			&i.Invite.InviterID,
			&i.Invite.MaxUses,
			&i.Invite.Uses,
			&i.Invite.ExpiresAt,
			&i.Invite.CreatedAt,
			&i.InviterUsername,
			&i.InviterDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemGuildInvite = `-- name: RedeemGuildInvite :one
UPDATE invites SET uses = uses + 1
WHERE code = $1
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR uses < max_uses)
RETURNING id, code, guild_id, channel_id, inviter_id, max_uses, uses, expires_at, created_at
`

// Spend one use of a live code, M10's RedeemInstanceInvite shape.
//
// Every guard is in the WHERE, so concurrent redemptions are decided by the row lock this UPDATE takes and
// the re-check READ COMMITTED does under it: exactly max_uses of them match. Written as a read and then an
// update, four of four of M10's concurrent racers got in. `max_uses IS NULL` is its own branch because
// `uses < NULL` is NULL, which would make an unlimited invite match nothing.
func (q *Queries) RedeemGuildInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, redeemGuildInvite, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GuildID,
		&i.ChannelID,
		&i.InviterID,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
