// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  []byte
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type DeviceCode struct {
	ID             int64
	DeviceCodeHash []byte
	UserCode       string
	DeviceID       string
	DeviceName     string
	UserID         *int64
	DeniedAt       pgtype.Timestamptz
	ConsumedAt     pgtype.Timestamptz
	LastPolledAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type EmailVerificationToken struct {
	ID         int64
	UserID     int64
	TokenHash  []byte
	SentTo     string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type InstanceAdmin struct {
	UserID    int64
	GrantedBy *int64
	GrantedAt pgtype.Timestamptz
}

type InstanceInvite struct {
	Code      string
	CreatedBy *int64
	MaxUses   *int32
	Uses      int32
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type OauthExchangeCode struct {
	ID            int64
	CodeHash      []byte
	UserID        int64
	FlowChallenge []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ConsumedAt    pgtype.Timestamptz
}

type OauthIdentity struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	Email          string
	CreatedAt      pgtype.Timestamptz
}

type OauthState struct {
	ID                int64
	StateHash         []byte
	Provider          string
	CodeVerifier      string
	FlowChallenge     []byte
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	ConsumedAt        pgtype.Timestamptz
	ClientRedirectUri string
	DeviceCodeID      *int64
}

type PasswordResetToken struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	SentTo    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type RegistrationReservation struct {
	Username  string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID               int64
	UserID           int64
	DeviceID         string
	RefreshTokenHash []byte
	DeviceName       *string
	IpAddress        *netip.Addr
	CreatedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	ReplacedByID     *int64
	FirstSeen        pgtype.Timestamptz
}

type User struct {
	ID              int64
	Username        string
	Email           string
	PasswordHash    *string
	DisplayName     string
	AvatarHash      *string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}
