// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthExchangeCode = `-- name: ConsumeOAuthExchangeCode :one
UPDATE oauth_exchange_codes
SET consumed_at = now()
WHERE code_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, code_hash, user_id, created_at, expires_at, consumed_at
`

// Single-use and expiry in the WHERE clause, so a code seen in an address bar and replayed matches zero
// rows the second time rather than issuing a second token pair.
func (q *Queries) ConsumeOAuthExchangeCode(ctx context.Context, codeHash []byte) (OauthExchangeCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthExchangeCode, codeHash)
	var i OauthExchangeCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
UPDATE oauth_states
SET consumed_at = now()
WHERE state_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, state_hash, provider, code_verifier, created_at, expires_at, consumed_at
`

// Spends a state, with single-use and expiry both in the WHERE clause rather than in Go.
//
// A callback replayed — by a user refreshing the page, or by someone who captured the redirect — matches
// zero rows the second time and is failed before any token exchange happens. Reading the row, checking
// consumed_at in the service, then updating would let two exchanges run against one verifier, which is the
// single-use property PKCE depends on.
func (q *Queries) ConsumeOAuthState(ctx context.Context, stateHash []byte) (OauthState, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, stateHash)
	var i OauthState
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.Provider,
		&i.CodeVerifier,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createOAuthExchangeCode = `-- name: CreateOAuthExchangeCode :one
INSERT INTO oauth_exchange_codes (id, code_hash, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code_hash, user_id, created_at, expires_at, consumed_at
`

type CreateOAuthExchangeCodeParams struct {
	ID        int64
	CodeHash  []byte
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthExchangeCode(ctx context.Context, arg CreateOAuthExchangeCodeParams) (OauthExchangeCode, error) {
	row := q.db.QueryRow(ctx, createOAuthExchangeCode,
		arg.ID,
		arg.CodeHash,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i OauthExchangeCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (id, user_id, provider, provider_user_id, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_user_id, email, created_at
`

type CreateOAuthIdentityParams struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	Email          string
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthState = `-- name: CreateOAuthState :one

INSERT INTO oauth_states (id, state_hash, provider, code_verifier, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, state_hash, provider, code_verifier, created_at, expires_at, consumed_at
`

type CreateOAuthStateParams struct {
	ID           int64
	StateHash    []byte
	Provider     string
	CodeVerifier string
	ExpiresAt    pgtype.Timestamptz
}

// OAuth sign-in queries.
//
// Two tables with very different lifetimes: oauth_identities is a permanent link between an account and a
// provider, oauth_states is a single-use row that exists for the minutes between /authorize and /callback.
func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRow(ctx, createOAuthState,
		arg.ID,
		arg.StateHash,
		arg.Provider,
		arg.CodeVerifier,
		arg.ExpiresAt,
	)
	var i OauthState
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.Provider,
		&i.CodeVerifier,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (id, username, email, display_name, email_verified_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, display_name, avatar_hash, email_verified_at, created_at, updated_at, deleted_at
`

type CreateOAuthUserParams struct {
	ID              int64
	Username        string
	Email           string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
}

// An account created by an OAuth sign-in, with no password.
//
// password_hash is left NULL rather than set to an empty string, so an account that can only sign in
// through a provider is distinguishable from one with a password — the distinction VerifyPassword and the
// reset path both already depend on.
func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpiredOAuthExchangeCodes = `-- name: DeleteExpiredOAuthExchangeCodes :execrows
DELETE FROM oauth_exchange_codes
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthExchangeCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthExchangeCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :execrows
DELETE FROM oauth_states
WHERE expires_at < now()
`

// Abandoned flows are the common case: opening the provider page and closing the tab leaves a row behind.
// Called by the cleanup job (M11); until then the table's growth is bounded only by traffic.
func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT i.id, i.user_id, i.provider, i.provider_user_id, i.email, i.created_at FROM oauth_identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1 AND i.provider_user_id = $2
  AND u.deleted_at IS NULL
`

type GetOAuthIdentityParams struct {
	Provider       string
	ProviderUserID string
}

// The sign-in lookup: has this provider account been linked before, to an account that still exists?
//
// The join is the load-bearing part, and its absence was a real hole. A soft-deleted account keeps its
// rows so authored content still renders as "Deleted User" — including its oauth_identities row — so a
// lookup on the identity alone let a deleted account sign straight back in and collect a token pair, while
// password login and API tokens both refused it. Same reasoning and same shape as
// GetActiveAPITokenByHash's join.
//
// Served by the UNIQUE constraint on (provider, provider_user_id) plus the users primary key, so neither
// needs a separate index.
func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentityIncludingDeleted = `-- name: GetOAuthIdentityIncludingDeleted :one
SELECT id, user_id, provider, provider_user_id, email, created_at FROM oauth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityIncludingDeletedParams struct {
	Provider       string
	ProviderUserID string
}

// The same lookup as GetOAuthIdentity, deliberately without the liveness join.
//
// Used only after a unique violation, to find out which of oauth_identities' two constraints was hit and
// what it means. GetOAuthIdentity hides rows belonging to soft-deleted accounts, which is correct for
// signing in and exactly wrong here: a hidden row is still a row, and it is the reason the INSERT failed.
func (q *Queries) GetOAuthIdentityIncludingDeleted(ctx context.Context, arg GetOAuthIdentityIncludingDeletedParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityIncludingDeleted, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOAuthExchangeCodesForUser = `-- name: RevokeOAuthExchangeCodesForUser :execrows
UPDATE oauth_exchange_codes
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Part of revoking everything a compromised credential could reach (CLAUDE.md rule 17).
//
// An outstanding exchange code is not a session, so revoking sessions and API tokens leaves it redeemable
// — and it is the one credential in this flow that gets rendered on screen. Without this, resetting a
// password to lock an intruder out still leaves them a code they can trade for a fresh token pair.
//
// No index on user_id, on purpose: the table only ever holds sign-ins from the last couple of minutes that
// nobody has redeemed yet, so a scan here is cheaper than the write this would add to every sign-in.
func (q *Queries) RevokeOAuthExchangeCodesForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthExchangeCodesForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
