// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, user_id, token_hash, sent_to, created_at, expires_at, used_at
`

// Spends a token, and does the single-use check in the WHERE clause rather than in Go.
//
// Two confirms racing on the same token both reach this statement; the second finds used_at already set,
// matches zero rows, and is failed. Checking `used_at IS NULL` in the service and updating afterwards
// would let both win and would make the "single-use" promise a comment rather than a guarantee.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id int64) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.SentTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (id, user_id, token_hash, sent_to, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, sent_to, created_at, expires_at, used_at
`

type CreatePasswordResetTokenParams struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	SentTo    string
	ExpiresAt pgtype.Timestamptz
}

// Password-reset token queries.
//
// A token is single-use and short-lived, and every one of these statements is written so that property
// holds in SQL rather than in whichever Go path remembered to check it.
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.SentTo,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.SentTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens
WHERE expires_at < now()
`

// Removes spent and expired reset tokens. Run on a schedule by auth.RunSweeper.
//
// Both are dead: ConsumePasswordResetToken already refuses anything expired or used, so nothing here is
// reachable and the rows are only taking space. Served by password_reset_tokens_expires_at_idx, made
// non-partial in 000005 for exactly this query.
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, sent_to, created_at, expires_at, used_at FROM password_reset_tokens
WHERE token_hash = $1
`

// The confirm path's only lookup. Deliberately returns spent and expired rows too: the caller needs to
// tell "no such token" from "already used" for its own logging, even though both are reported to the
// client identically.
func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.SentTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const invalidateOutstandingResetTokens = `-- name: InvalidateOutstandingResetTokens :execrows
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

// Requesting a new reset spends every older one for that account, so the most recent link is the only one
// that works. Without this, every request an anxious user makes leaves another live token behind, and the
// window a leaked one is redeemable in becomes the union of all of them.
func (q *Queries) InvalidateOutstandingResetTokens(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateOutstandingResetTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, display_name, avatar_hash, email_verified_at, created_at, updated_at, deleted_at
`

type SetUserPasswordParams struct {
	ID           int64
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
