// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Records who authorized this device.
	//
	// `user_id IS NULL` is what makes an approval single-use, and it is the reason the approval token needs
	// no store of its own: replaying one matches zero rows. The remaining conditions mean an approval racing
	// a denial or an expiry loses rather than overwriting it.
	ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) (DeviceCode, error)
	// The moment the factor becomes required. Guarded on still being unconfirmed so a replayed confirmation
	// cannot move the timestamp, which is the same single-transition discipline the device flow uses.
	ConfirmTOTP(ctx context.Context, userID int64) (UserTotp, error)
	// Spends an approved code for the one token pair it is worth.
	//
	// Single-use in the WHERE clause, for the reason ConsumeOAuthExchangeCode gives: two processes holding
	// the same device code both reach here, and exactly one matches a row. Reading, checking consumed_at in
	// Go, then updating would issue two sessions for one authorization.
	ConsumeDeviceCode(ctx context.Context, deviceCodeHash []byte) (DeviceCode, error)
	// Spends a token, with single-use in the WHERE clause rather than in Go.
	//
	// Two confirms racing on the same link both reach this statement; the second finds consumed_at already set,
	// matches zero rows, and is failed. Checking in the service and updating afterwards would let both win, and
	// while a double verification is harmless in itself, the guarantee is what the address-change check below
	// depends on.
	ConsumeEmailVerificationToken(ctx context.Context, id int64) (EmailVerificationToken, error)
	// Single-use and expiry in the WHERE clause, so a code seen in an address bar and replayed matches zero
	// rows the second time rather than issuing a second token pair.
	ConsumeOAuthExchangeCode(ctx context.Context, codeHash []byte) (OauthExchangeCode, error)
	// Spends a state, with single-use and expiry both in the WHERE clause rather than in Go.
	//
	// A callback replayed — by a user refreshing the page, or by someone who captured the redirect — matches
	// zero rows the second time and is failed before any token exchange happens. Reading the row, checking
	// consumed_at in the service, then updating would let two exchanges run against one verifier, which is the
	// single-use property PKCE depends on.
	ConsumeOAuthState(ctx context.Context, stateHash []byte) (OauthState, error)
	// Spends a token, and does the single-use check in the WHERE clause rather than in Go.
	//
	// Two confirms racing on the same token both reach this statement; the second finds used_at already set,
	// matches zero rows, and is failed. Checking `used_at IS NULL` in the service and updating afterwards
	// would let both win and would make the "single-use" promise a comment rather than a guarantee.
	ConsumePasswordResetToken(ctx context.Context, id int64) (PasswordResetToken, error)
	// Spend one code, exactly once.
	//
	// Every guard is in the WHERE: the code must belong to this account, and must not already be spent. Two
	// requests presenting the same code both reach this statement and Postgres serializes them on the row, so
	// the second re-evaluates `used_at IS NULL` against the first's committed value and matches nothing. A
	// read-then-update in Go would let both through, which is the shape RedeemInstanceInvite was rewritten out
	// of at M10 after four of four concurrent racers got in.
	//
	// Scoped by user_id as well as the hash even though the hash is unique, for the reason every revoking
	// query in sessions.sql is scoped by device: a lookup that can only ever match this account's rows cannot
	// be made to act on another's by a collision or a future schema change.
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (UserRecoveryCode, error)
	// The bootstrap guard, and the reason it is a count rather than an existence check.
	//
	// POST /instance/bootstrap is authorized by an operator token, which is minted from the instance signing
	// key by anyone holding the config file. That is the right authority for creating the *first* admin and
	// the wrong one for creating a second — an operator token replayed later must not be able to add an
	// account to this table quietly. So the endpoint refuses unless this answers 0, which makes bootstrap
	// self-disabling rather than needing a flag somewhere that says whether it already ran.
	//
	// Called after LockInstanceBootstrap and inside the same transaction as the insert. Both halves are
	// required: the lock is what makes the count a decision rather than an observation.
	CountInstanceAdmins(ctx context.Context) (int64, error)
	// Served by user_recovery_codes_live_idx (000014). Read by the profile response and by the regenerate
	// path, so it scales with the codes an account has left rather than with every set it has ever had.
	CountLiveRecoveryCodes(ctx context.Context, userID int64) (int64, error)
	CountLiveSessionsForDevice(ctx context.Context, arg CountLiveSessionsForDeviceParams) (int64, error)
	// Scoped API token queries.
	//
	// These are the long-lived, narrow-privilege credentials bots and local automation use, as opposed to the
	// 15-minute access tokens a logged-in client holds. They are stored only as a SHA-256 hash, so the raw
	// value is recoverable exactly once — in the response that created it.
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	// Device-code flow queries (Milestone M9).
	//
	// One table with a short life and a small state machine: issued, then approved or denied by a browser
	// somewhere else, then spent exactly once by the client that has been polling for it. Every transition
	// that must happen at most once is expressed as a WHERE clause here rather than as a check in Go, so two
	// concurrent attempts produce one winner without anything in the service having to remember to look.
	// device_id and device_name come from the client asking for the code, which is the client that will hold
	// the resulting session. The browser that approves never supplies either.
	CreateDeviceCode(ctx context.Context, arg CreateDeviceCodeParams) (DeviceCode, error)
	// Email verification queries.
	//
	// The same shape as password_reset_tokens and deliberately so: two token tables with different rules about
	// single-use or expiry would be two sets of guards to keep right, and the second one is always the one
	// that gets it wrong.
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	// granted_by is NULL for the bootstrap admin: nobody in this table granted it. See 000008.
	CreateInstanceAdmin(ctx context.Context, arg CreateInstanceAdminParams) (InstanceAdmin, error)
	// created_by is NULL when the instance operator issued it, who is not an account. See 000009.
	CreateInstanceInvite(ctx context.Context, arg CreateInstanceInviteParams) (InstanceInvite, error)
	CreateOAuthExchangeCode(ctx context.Context, arg CreateOAuthExchangeCodeParams) (OauthExchangeCode, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	// OAuth sign-in queries.
	//
	// Two tables with very different lifetimes: oauth_identities is a permanent link between an account and a
	// provider, oauth_states is a single-use row that exists for the minutes between /authorize and /callback.
	// Two columns decide where a completed flow ends, and at most one of them is ever set.
	//
	// client_redirect_uri is '' for a flow with nowhere to return to — a browser, and a device flow.
	// device_code_id is NULL except for a flow started from the device verification page (M9). Both are
	// written once here and only ever read back out of the row ConsumeOAuthState spends, which is what keeps
	// the destination a property of the flow rather than of whoever presents the callback.
	CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (OauthState, error)
	// An account created by an OAuth sign-in, with no password.
	//
	// password_hash is left NULL rather than set to an empty string, so an account that can only sign in
	// through a provider is distinguishable from one with a password — the distinction VerifyPassword and the
	// reset path both already depend on.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	// Password-reset token queries.
	//
	// A token is single-use and short-lived, and every one of these statements is written so that property
	// holds in SQL rather than in whichever Go path remembered to check it.
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (UserRecoveryCode, error)
	// Refresh-session queries.
	//
	// A session is one device's refresh-token family. Rotation replaces a row with a successor and links the
	// two; reuse detection walks that link. Every one of these queries is scoped by user_id AND device_id
	// wherever it revokes, because revoking across devices is precisely the bug this schema exists to prevent
	// (docs/architecture.md §2, ADR 0011).
	// first_seen is the family's start and is carried forward by rotation, never recomputed — see 000013. A
	// fresh sign-in passes its own created_at; a rotation passes the predecessor's value along.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Account queries.
	//
	// Every read filters `deleted_at IS NULL`: a soft-deleted account keeps its row so authored content can
	// still render as "Deleted User", but it must never be findable for login, registration collision, or
	// profile lookup. Leaving that filter off is the way a deleted account quietly becomes usable again.
	// email_verified_at is a parameter rather than a default, because the three callers disagree about it and
	// each is right.
	//
	// Registration passes NULL: the address is a claim until somebody follows a link sent to it. Bootstrap
	// passes now(), because the operator proved filesystem access to the instance's own config, which is
	// strictly more than an emailed link proves — asking them to check their mail to finish setting up a
	// server they are holding the keys to would be theatre, and would make bootstrap impossible on an
	// instance with no relay. The OAuth path has its own insert (CreateOAuthUser) because it creates an
	// account with no password at all.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Called by auth.RunSweeper. Abandoned authorizations are the common case, and the endpoint that creates
	// them is unauthenticated, so nothing but the rate limiter bounds how fast this table grows.
	DeleteExpiredDeviceCodes(ctx context.Context) (int64, error)
	// Called by auth.RunSweeper. Non-partial index behind it — see 000010, and 000005 for why.
	DeleteExpiredEmailVerificationTokens(ctx context.Context) (int64, error)
	// Called by auth.RunSweeper.
	//
	// The IS NOT NULL is redundant against SQL's own semantics — a NULL expires_at makes the comparison NULL
	// rather than true, so a never-expiring invite is already skipped — and it is here anyway, because that is
	// a fact about three-valued logic rather than about this table, and the row it would wrongly delete is one
	// an administrator deliberately made permanent.
	//
	// Unlike the other swept tables, these rows are not garbage the moment they expire: this is the only sweep
	// that removes something a person created on purpose. It is still right — an expired invite is refused by
	// RedeemInstanceInvite regardless, so the row has no effect on anything except the administrator's list.
	DeleteExpiredInstanceInvites(ctx context.Context) (int64, error)
	DeleteExpiredOAuthExchangeCodes(ctx context.Context) (int64, error)
	// Abandoned flows are the common case: opening the provider page and closing the tab leaves a row behind.
	// Called by auth.RunSweeper. Without it the table grows for the life of the instance, and it is written
	// by an unauthenticated endpoint, so nothing but the rate limiter bounds that.
	DeleteExpiredOAuthStates(ctx context.Context) (int64, error)
	// Removes spent and expired reset tokens. Run on a schedule by auth.RunSweeper.
	//
	// Both are dead: ConsumePasswordResetToken already refuses anything expired or used, so nothing here is
	// reachable and the rows are only taking space. Served by password_reset_tokens_expires_at_idx, made
	// non-partial in 000005 for exactly this query.
	DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error)
	// Called by auth.RunSweeper, in batches. Non-partial index behind it and an index on replaced_by_id — see
	// 000012, and 000005 for why a partial one cannot serve this.
	//
	// Expired only, never merely revoked, and the distinction is load-bearing. A revoked row is still
	// evidence: replaced_by_id is what lets a presented token be told apart as *replay* rather than as merely
	// unknown, and that is the signal reuse detection revokes a device family on. Deleting revoked rows while
	// their tokens could still be presented would turn a stolen token into an unrecognized one and quietly
	// disable the detection. Past expires_at nothing can be presented, so the evidence has nothing left to
	// prove.
	//
	// One consequence worth naming, because it is a behavior change rather than a neutral cleanup. Refresh
	// tests revoked_at and replaced_by_id *before* it tests expiry, so today presenting a long-expired rotated
	// token is detected as replay and revokes that device's whole family. Once the row is swept the same
	// presentation is merely an unknown token and the family survives. No access is granted either way — the
	// token is unredeemable in both — but a detection that fires now stops firing. Accepted: acting on a
	// month-old unredeemable token means logging a legitimate user out of every device on that machine on the
	// strength of a signal that cannot lead anywhere.
	//
	// Bounded, unlike the other six sweeps, because this table is unlike them. Theirs hold rows with TTLs of
	// minutes to an hour, so a ten-minute tick keeps them small. This one has never been swept at all: the
	// first pass on an instance running since M4 faces the entire backlog, every deleted row fires the
	// replaced_by_id RI trigger, and RunSweeper passes the process context with no deadline. Unbounded, that
	// is one statement holding a connection from a deliberately small pool (§15.3) for as long as it takes,
	// uncancellable short of shutdown. The loop in SweepExpired calls this until it returns less than the
	// limit, so a large backlog is drained across several bounded statements instead of one unbounded one.
	DeleteExpiredSessions(ctx context.Context, limit int32) (int64, error)
	// Revocation. execrows rather than :exec so the caller can tell a code that was deleted from one that was
	// never there, which is the difference between "done" and "check what you typed".
	DeleteInstanceInvite(ctx context.Context, code string) (int64, error)
	// Used when the whole set is replaced or the factor is disabled. Deletes rather than marking spent: these
	// are not evidence of anything once the factor they belonged to is gone.
	DeleteRecoveryCodesForUser(ctx context.Context, userID int64) (int64, error)
	DeleteTOTPForUser(ctx context.Context, userID int64) (int64, error)
	// The other half of the approval page, and the reason it is worth a column rather than letting the code
	// expire: a person who realizes they were sent a code by someone else can end the authorization now, and
	// the waiting client stops immediately instead of polling for another twenty minutes.
	DenyDeviceCode(ctx context.Context, id int64) (DeviceCode, error)
	// Runs on every request authenticated with an API token, which is why the hash column is indexed.
	//
	// One statement, not three: the owning account's liveness is joined in rather than fetched separately, and
	// the revocation and soft-delete filters are applied here rather than in Go. An unusable token therefore
	// returns no rows whatever the reason — which is also what the client is told, so nothing is lost by not
	// distinguishing them.
	GetActiveAPITokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error)
	// The verification page's re-read between steps.
	//
	// By id because that is what the signed continuation carries: the device code never reaches the browser at
	// all, and the user code is what a person types, so putting either back into a value the browser holds
	// would give a page something to replay. Same liveness conditions as the lookup by user code, so an
	// authorization that expired or was decided while somebody was typing is caught at every step rather than
	// only at the first.
	GetDeviceCodeByID(ctx context.Context, id int64) (DeviceCode, error)
	// The verification page's lookup, for a code that can still be acted on.
	//
	// Approved, denied, spent and expired rows are all excluded, so all four produce the same "no such code"
	// as a code that never existed. That is worth having beyond tidiness: a code entered a second time gets
	// told the authorization is over, instead of being walked through a sign-in that would then fail at the
	// approval step for a reason nobody could see.
	GetDeviceCodeByUserCode(ctx context.Context, userCode string) (DeviceCode, error)
	// The confirm path's lookup. Expiry is checked here as well as in the consume below, so an expired token
	// is refused before anything is written — the same two-step the reset path uses.
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	// The sign-in lookup: has this provider account been linked before, to an account that still exists?
	//
	// The join is the load-bearing part, and its absence was a real hole. A soft-deleted account keeps its
	// rows so authored content still renders as "Deleted User" — including its oauth_identities row — so a
	// lookup on the identity alone let a deleted account sign straight back in and collect a token pair, while
	// password login and API tokens both refused it. Same reasoning and same shape as
	// GetActiveAPITokenByHash's join.
	//
	// Served by the UNIQUE constraint on (provider, provider_user_id) plus the users primary key, so neither
	// needs a separate index.
	GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error)
	// The same lookup as GetOAuthIdentity, deliberately without the liveness join.
	//
	// Used only after a unique violation, to find out which of oauth_identities' two constraints was hit and
	// what it means. GetOAuthIdentity hides rows belonging to soft-deleted accounts, which is correct for
	// signing in and exactly wrong here: a hidden row is still a row, and it is the reason the INSERT failed.
	GetOAuthIdentityIncludingDeleted(ctx context.Context, arg GetOAuthIdentityIncludingDeletedParams) (OauthIdentity, error)
	// The confirm path's only lookup. Deliberately returns spent and expired rows too: the caller needs to
	// tell "no such token" from "already used" for its own logging, even though both are reported to the
	// client identically.
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	// Deliberately returns revoked and rotated rows, exactly as GetSessionByRefreshTokenHash does.
	//
	// The caller that needs this is "which device is this request coming from", answered from the sid claim in
	// the access token. That claim names the session the token was minted from, and a rotation inside the
	// token's fifteen-minute life revokes that row while the token stays valid. Filtering revoked rows here
	// would make every recently-refreshed client look like it had no current device — and POST /auth/logout/all
	// would then spare nothing and log the caller out of itself.
	GetSessionByID(ctx context.Context, id int64) (Session, error)
	// The hot path: every refresh looks a session up by hash. Deliberately returns revoked and rotated rows
	// too — the caller must be able to tell "no such token" from "a token that was already used", since only
	// the second is a replay worth revoking a family over.
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error)
	// Deliberately returns unconfirmed rows. "Is a factor owed" and "is an enrollment in progress" are
	// different questions and the caller asks both; a query that hid unconfirmed rows would make the second
	// unanswerable and silently let a second enrollment overwrite one in flight.
	GetTOTPForUser(ctx context.Context, userID int64) (UserTotp, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Requesting a new reset spends every older one for that account, so the most recent link is the only one
	// that works. Without this, every request an anxious user makes leaves another live token behind, and the
	// window a leaked one is redeemable in becomes the union of all of them.
	InvalidateOutstandingResetTokens(ctx context.Context, userID int64) (int64, error)
	// Requesting verification again spends every older token for that account, so the newest link is the only
	// one that works. Without it, each resend leaves another live token behind and the window a leaked mail is
	// redeemable in becomes the union of all of them.
	InvalidateOutstandingVerificationTokens(ctx context.Context, userID int64) (int64, error)
	// The tier check, on every request to an instance-administration endpoint.
	//
	// Joined against users for liveness, the same shape and the same reasoning as GetActiveAPITokenByHash
	// and GetOAuthIdentity: a soft-deleted account keeps its rows so its authored content still renders as
	// "Deleted User", and this row is one of them. Without the join, deleting an admin's account would leave
	// their tier intact and usable by any credential still outstanding on it.
	IsInstanceAdmin(ctx context.Context, userID int64) (bool, error)
	ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error)
	// Everything outstanding, newest first.
	//
	// Deliberately includes exhausted and expired rows. An administrator asking "what invites exist" is
	// usually asking why somebody could not use one, and a list that silently omits the answer is worse than
	// one they have to read. The sweep removes expired rows eventually; nothing removes exhausted ones, since
	// `3 of 3 used` is the record of an invite having done its job.
	//
	// No index needed: an instance holds tens of these, not thousands, and this is an administrator-facing
	// call made by hand. An index on created_at would be a write on every registration to serve a query
	// nobody makes in a loop.
	ListInstanceInvites(ctx context.Context) ([]InstanceInvite, error)
	// The devices signed in to an account: one row per device family, not one per session row.
	//
	// A session row is one generation of a rotating family, replaced every time the client refreshes. Listing
	// rows would show somebody a new "session" every fifteen minutes and hand out ids that are stale before
	// they can be acted on, so DISTINCT ON collapses each family to its newest live row — whose id is what the
	// revoke endpoint takes.
	//
	// first_seen is read straight off that row rather than aggregated over the family. It used to be
	// min(created_at) across every row including revoked ones, which was correct until 000012 started deleting
	// them: after a sweep no row older than the refresh TTL survives, so the aggregate reported a rolling
	// thirty days for a device somebody had used for a year. 000013 carries the value forward instead.
	//
	// Sorted by last use in the outer query because DISTINCT ON dictates the inner ORDER BY, and "which of
	// these is the one I am still using" is the question somebody scanning this list is asking.
	// Served by sessions_live_by_device_idx (000013).
	ListSessionDevicesForUser(ctx context.Context, userID int64) ([]ListSessionDevicesForUserRow, error)
	// Instance-administration queries.
	//
	// The Instance Admin tier, which is instance-wide and sits outside roles.Resolve entirely (ADR 0013).
	// M10 creates the first row and reads it; M71 adds granting, revoking, and the last-admin safety rail.
	// Serializes bootstrap attempts across processes, for the whole of the calling transaction.
	//
	// CountInstanceAdmins below is checked and then acted on, which under READ COMMITTED — Postgres's default
	// and this pool's — is a read-modify-write with a gap in it. Two concurrent bootstraps both see zero, both
	// insert a different user_id, and the primary key stops neither: the instance ends up with two
	// administrators, one of whom nobody intended and no audit record explains.
	//
	// An advisory lock rather than row locking, because there is nothing to lock: the guard is the *absence*
	// of rows, and SELECT ... FOR UPDATE over an empty table locks nothing at all. Taken as an xact lock so it
	// is released by commit or rollback without any unlock call to forget.
	//
	// The key follows internal/platform/database's convention: "NORITE" in ASCII plus a slot number, so it is
	// recognizable in pg_locks. Slot 1 is the migration lock; this is slot 2. Written in decimal because
	// sqlc parses the literal, and the value is 0x4E4F524954450002 — "NORITE" then 0x0002.
	LockInstanceBootstrap(ctx context.Context) error
	// Records that the address is confirmed.
	//
	// The WHERE guards against a race with an address change: the account's current email must still be the
	// one the token was sent to. ConsumeEmailVerificationToken has already checked that the token is unspent,
	// but the address can change between the two statements, and they run in one transaction precisely so this
	// comparison is against a value that cannot move underneath it.
	MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (User, error)
	// Spend a time-step, exactly once.
	//
	// The guard is in the WHERE, like every other single-use statement in this package: two requests presenting
	// the same code both reach it and Postgres serializes them on the row, so the second re-evaluates
	// `last_used_step < $2` against the first's committed value and matches nothing. A read-then-update in Go
	// would let both through, which is the shape ConsumeRecoveryCode and RedeemInstanceInvite are written out
	// of.
	//
	// Strictly greater, so a code from an *earlier* step inside the skew window cannot be replayed after a
	// later one has been accepted — which is the case a naive "record the newest" would miss.
	MarkTOTPStepUsed(ctx context.Context, arg MarkTOTPStepUsedParams) (int64, error)
	// Health-check queries.
	//
	// These exist so the readiness endpoint validates the *whole* data path — pool checkout, the
	// sqlc-generated call, the round trip to Postgres — rather than only the socket. A pool that has a live
	// TCP connection but cannot actually execute a statement (exhausted, wedged on a failover, blocked by a
	// broken search_path) is not ready, and a bare ping would report it as healthy.
	Ping(ctx context.Context) (int32, error)
	// One poll: records that it happened and reports the state as it was *before* it did.
	//
	// The CTE is what makes the previous poll time readable at all. RETURNING sees the updated row, so
	// last_polled_at there is always now() and always useless; `previous` is evaluated against the same
	// statement snapshot and therefore holds the value from the poll before this one. That is what the
	// slow_down decision is made against.
	//
	// The row is touched even when the poll came too soon, deliberately: a client hammering every second must
	// keep being told to slow down, and only updating on well-behaved polls would let the first one reset the
	// clock forever.
	//
	// `too_soon` is computed here rather than in Go, and that is not a style preference. last_polled_at is
	// written by this database's now(); comparing it against the *application's* clock measures the difference
	// between two machines as well as the gap between two polls. A client at exactly the published interval
	// has only a round trip of margin, so a database node running a few tens of milliseconds ahead would
	// answer slow_down to every well-behaved poll, and one running behind would make the interval
	// unenforceable. Both are routine between two pods and neither is visible in a test that fakes the clock.
	//
	// Expired and already-spent rows match nothing, which the service reports as one answer.
	PollDeviceCode(ctx context.Context, arg PollDeviceCodeParams) (PollDeviceCodeRow, error)
	// Instance invite queries.
	//
	// The codes that gate account creation while registration_mode = "invite". Distinct from the per-guild
	// `invites` table, which admits an existing account to a guild.
	// Spends one use of an invite, with every guard in the WHERE clause rather than in Go.
	//
	// This is the whole of the concurrency story, and it has to be: two people redeeming a one-use code at the
	// same moment both read `uses = 0`, and a check-then-update in the service would let both through. As a
	// single statement, Postgres serializes the two updates on the row itself — the second re-evaluates the
	// WHERE against the first's committed value and matches nothing. Exactly the shape
	// ConsumePasswordResetToken uses for single-use, generalized from one use to n.
	//
	// Both NULLs mean "unlimited" and "never expires", and both are written as explicit IS NULL branches
	// rather than left to three-valued logic: `uses < NULL` is NULL, not true, so an unlimited invite would
	// match nothing at all and the most permissive setting would be the most restrictive one.
	//
	// Zero rows is the only failure this reports, and it deliberately does not say which guard refused. An
	// unknown code, an exhausted one and an expired one are one answer to the caller — the same treatment
	// every credential lookup in this package gets, and here it also stops the endpoint from being a way to
	// probe which codes exist.
	RedeemInstanceInvite(ctx context.Context, code string) (InstanceInvite, error)
	// Claims a username for a registration that created no account.
	//
	// ON CONFLICT DO NOTHING because the name may already be claimed by an account or by an earlier
	// reservation, and either way the caller's answer is the same: it is not available. Nothing here needs to
	// know which.
	ReserveUsername(ctx context.Context, username string) error
	// Scoped by user_id as well as id: an actor may only revoke their own tokens, and enforcing that in the
	// statement means a handler cannot forget to check ownership (CLAUDE.md rule 1).
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (ApiToken, error)
	// Every API token the account holds.
	//
	// Moved here from password_reset_tokens.sql at M11, for the reason RevokeAllSessionsForUser gives. The
	// argument for revoking these alongside sessions moved with it, onto auth.revokeEverything.
	RevokeAllAPITokensForUser(ctx context.Context, userID int64) (int64, error)
	// Every live session for an account, across every device.
	//
	// Moved here from password_reset_tokens.sql at M11, where M5 had put it because reset was its only caller.
	// It belongs to sessions now: auth.revokeEverything is what calls it, and reset is one of that primitive's
	// callers rather than its owner (CLAUDE.md rule 17).
	RevokeAllSessionsForUser(ctx context.Context, userID int64) (int64, error)
	// The same, sparing one device — what "sign out everywhere else" means.
	//
	// The spared device is named rather than the spared session, because a session is one row of a rotating
	// family: sparing a row would leave the caller signed in only until its next refresh, which is at most
	// fifteen minutes away.
	RevokeAllSessionsForUserExceptDevice(ctx context.Context, arg RevokeAllSessionsForUserExceptDeviceParams) (int64, error)
	// Takes back an approval that has not been collected yet.
	//
	// This is what makes Deny a real recovery path rather than a promise. Somebody who approves and realizes a
	// second later — the likeliest way anybody escapes the phishing this flow is vulnerable to — presses Deny
	// and lands here, because DenyDeviceCode by then matches nothing. Spending the code is the strongest thing
	// still available: the waiting client's next poll gets expired_token and no session is ever created.
	//
	// Scoped to the account the approval token names, so an approval for one account cannot revoke another's.
	// Matches nothing once the code has been redeemed, which is the one case where this is too late and the
	// caller has to say so.
	RevokeApprovedDeviceCode(ctx context.Context, arg RevokeApprovedDeviceCodeParams) (DeviceCode, error)
	// Part of revoking everything a compromised credential could reach (CLAUDE.md rule 17).
	//
	// An approved-but-unpolled device code is exactly the same kind of outstanding claim on an account as an
	// OAuth exchange code, and RevokeOAuthExchangeCodesForUser exists for that reason — this one closes the
	// same hole on the path M9 adds. Without it, a password reset performed to lock an intruder out leaves
	// them a code that still trades for a fresh token pair.
	//
	// Rows still waiting for approval have a NULL user_id and belong to nobody yet, so they are correctly
	// outside this. No index on user_id, for the reason RevokeOAuthExchangeCodesForUser gives: the table
	// holds minutes of unfinished sign-ins, so a scan is cheaper than a write on every issuance.
	RevokeDeviceCodesForUser(ctx context.Context, userID *int64) (int64, error)
	// Part of revoking everything a compromised credential could reach (CLAUDE.md rule 17).
	//
	// An outstanding exchange code is not a session, so revoking sessions and API tokens leaves it redeemable
	// — and it is the one credential in this flow that gets rendered on screen. Without this, resetting a
	// password to lock an intruder out still leaves them a code they can trade for a fresh token pair.
	//
	// No index on user_id, on purpose: the table only ever holds sign-ins from the last couple of minutes that
	// nobody has redeemed yet, so a scan here is cheaper than the write this would add to every sign-in.
	RevokeOAuthExchangeCodesForUser(ctx context.Context, userID int64) (int64, error)
	RevokeSession(ctx context.Context, id int64) (Session, error)
	// Reuse detection: revoke every live session in one device's family. Scoped by device_id as well as
	// user_id so another machine's family is untouched — a user with daemons on two computers must not be
	// logged out of one because the other replayed a token.
	RevokeSessionsForDevice(ctx context.Context, arg RevokeSessionsForDeviceParams) (int64, error)
	// Marks a session as replaced by its successor. Revoking at the same moment is what makes the old token
	// single-use: a second presentation finds revoked_at set and replaced_by_id populated, which is the replay
	// signature.
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error)
	// Records use, at most once every few minutes per token.
	//
	// Writing on every authenticated request would put a row update — and its WAL traffic, and its dead tuple
	// for autovacuum — on the hottest read path in the API, to keep a timestamp accurate to the second that
	// nothing needs to the second. The staleness window is the whole optimization: "last used" is for an
	// operator auditing an account's tokens, and five minutes is well inside what that reader cares about.
	//
	// Still fire-and-forget: bookkeeping must never be able to fail an otherwise-valid request.
	TouchAPIToken(ctx context.Context, id int64) error
	// Second-factor queries: one TOTP enrollment per account, and its recovery codes.
	//
	// Single-use lives in the statement here as it does everywhere else in this package — see
	// ConsumeRecoveryCode below, and password_reset_tokens.sql for the reasoning it shares.
	// Begin (or restart) enrollment. Unconfirmed until a code proves the authenticator works.
	//
	// ON CONFLICT replaces rather than refusing, because the case it serves is somebody who lost the QR code
	// half-way and started again. Confirming is what makes a factor real, so replacing an *unconfirmed* row
	// costs nothing — and replacing a confirmed one is prevented by the caller, which requires the current
	// factor before it will touch an account that already has one.
	UpsertTOTPEnrollment(ctx context.Context, arg UpsertTOTPEnrollmentParams) (UserTotp, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	// Is this username claimed, by an account or by a registration that created none?
	//
	// The second half is what closes the last leg of the registration oracle, and it is not optional: a
	// registration against a *taken* address creates no account, so without a reservation it would leave the
	// username free while one against a fresh address does not — and two requests read that difference. See
	// migration 000011.
	//
	// One query rather than two so the two halves cannot be checked in different places, or one of them
	// forgotten by a later caller.
	UsernameUnavailable(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
