// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one

INSERT INTO reports (id, reporter_id, target_type, target_id, guild_id, reason_category, detail, routed_to)
VALUES ($1, $2, $3, $4, $7::bigint, $5, $8::text, $6)
RETURNING id, reporter_id, target_type, target_id, guild_id, reason_category, detail, status, routed_to, resolved_by, created_at, resolved_at
`

type CreateReportParams struct {
	ID             int64
	ReporterID     int64
	TargetType     int16
	TargetID       int64
	ReasonCategory string
	RoutedTo       int16
	GuildID        *int64
	Detail         *string
}

// Milestone M16 — filing a report, and the guild-moderator triage queue that reads it.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.ReasonCategory,
		arg.RoutedTo,
		arg.GuildID,
		arg.Detail,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.GuildID,
		&i.ReasonCategory,
		&i.Detail,
		&i.Status,
		&i.RoutedTo,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getGuildReport = `-- name: GetGuildReport :one
SELECT
  r.id, r.reporter_id, r.target_type, r.target_id, r.guild_id, r.reason_category, r.detail, r.status, r.routed_to, r.resolved_by, r.created_at, r.resolved_at,
  mv.content AS target_content,
  m.is_e2e AS target_is_e2e,
  m.deleted_at AS target_deleted_at,
  m.channel_id AS target_channel_id,
  m.author_id AS target_author_id
FROM reports r
LEFT JOIN messages m ON m.id = r.target_id AND r.target_type = 0
LEFT JOIN messages mv ON mv.id = m.id AND NOT mv.is_e2e
WHERE r.id = $1 AND r.guild_id = $2
`

type GetGuildReportParams struct {
	ID      int64
	GuildID *int64
}

type GetGuildReportRow struct {
	Report          Report
	TargetContent   *string
	TargetIsE2e     *bool
	TargetDeletedAt pgtype.Timestamptz
	TargetChannelID *int64
	TargetAuthorID  *int64
}

// One report in full: the only place this milestone returns reported content.
//
// Scoped by guild_id as well as id, so a report id from another guild is not reachable through this
// guild's path — the permission check covers the guild in the route, and M15's loadInChannel established
// that a mismatch answers 404 rather than disclosing that the id exists elsewhere.
//
// # Rule 13, and why it is two joins rather than a CASE
//
// `m` resolves the target and supplies the two facts about it. `mv` is the same row again behind
// `NOT mv.is_e2e`, and it is the only thing content is read from — so an encrypted message contributes a
// NULL content and a true `target_is_e2e`, which are different answers the service can tell apart.
//
// The exclusion is a **join predicate rather than a CASE expression** for two reasons that happen to
// agree. Rule 13 asks for it to be explicit and in the query, where a later reader of this join inherits
// it instead of having to remember it — the same argument that puts the @everyone delete guard in the
// statement. And an expression defeats sqlc's nullability inference: `CASE WHEN m.is_e2e THEN NULL ELSE
// m.content END` generated an `interface{}`, and casting it to text generated a non-nullable `string`
// that a NULL fails to scan into. A plain column through a LEFT JOIN types as `*string` correctly, which
// ListGuildMemberAuthority has relied on since M12.
//
// Today `is_e2e` is never true for a guild channel — E2E is DM-only, a DM has no guild, and this surface
// is guild-scoped. That is precisely why the exclusion is written rather than argued: M11a's lesson is
// that "closed by construction" stops being true quietly, and it was given a test anyway.
func (q *Queries) GetGuildReport(ctx context.Context, arg GetGuildReportParams) (GetGuildReportRow, error) {
	row := q.db.QueryRow(ctx, getGuildReport, arg.ID, arg.GuildID)
	var i GetGuildReportRow
	err := row.Scan(
		&i.Report.ID,
		&i.Report.ReporterID,
		&i.Report.TargetType,
		&i.Report.TargetID,
		&i.Report.GuildID,
		&i.Report.ReasonCategory,
		&i.Report.Detail,
		&i.Report.Status,
		&i.Report.RoutedTo,
		&i.Report.ResolvedBy,
		&i.Report.CreatedAt,
		&i.Report.ResolvedAt,
		&i.TargetContent,
		&i.TargetIsE2e,
		&i.TargetDeletedAt,
		&i.TargetChannelID,
		&i.TargetAuthorID,
	)
	return i, err
}

const getMessageForReport = `-- name: GetMessageForReport :one
SELECT id, channel_id, author_id, content, type, reply_to_id, is_e2e, edited_at, deleted_at, created_at FROM messages WHERE id = $1
`

// The message a report is being filed against, deleted rows included.
//
// Deliberately not GetMessage, which filters `deleted_at IS NULL`. A message deleted seconds after it was
// posted is exactly what somebody reports, and refusing to file against one would make deleting fast the
// way to dodge a report. 000020 made the delete soft for this reason in as many words.
//
// Lives in this file rather than messages.sql because `reports` is its only caller and the difference from
// GetMessage is a reports decision, not a messages one — sqlc generates one package either way.
func (q *Queries) GetMessageForReport(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageForReport, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.Type,
		&i.ReplyToID,
		&i.IsE2e,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGuildReports = `-- name: ListGuildReports :many
SELECT
  r.id, r.reporter_id, r.target_type, r.target_id, r.guild_id, r.reason_category, r.detail, r.status, r.routed_to, r.resolved_by, r.created_at, r.resolved_at,
  m.is_e2e AS target_is_e2e,
  m.deleted_at AS target_deleted_at
FROM reports r
LEFT JOIN messages m ON m.id = r.target_id AND r.target_type = 0
WHERE r.guild_id = $1
  AND r.id < COALESCE($3::bigint, 9223372036854775807)
ORDER BY r.id DESC
LIMIT $2
`

type ListGuildReportsParams struct {
	GuildID *int64
	Limit   int32
	Before  *int64
}

type ListGuildReportsRow struct {
	Report          Report
	TargetIsE2e     *bool
	TargetDeletedAt pgtype.Timestamptz
}

// The same page across every status. See above for why this is a second query rather than a filter.
func (q *Queries) ListGuildReports(ctx context.Context, arg ListGuildReportsParams) ([]ListGuildReportsRow, error) {
	rows, err := q.db.Query(ctx, listGuildReports, arg.GuildID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildReportsRow{}
	for rows.Next() {
		var i ListGuildReportsRow
		if err := rows.Scan(
			&i.Report.ID,
			&i.Report.ReporterID,
			&i.Report.TargetType,
			&i.Report.TargetID,
			&i.Report.GuildID,
			&i.Report.ReasonCategory,
			&i.Report.Detail,
			&i.Report.Status,
			&i.Report.RoutedTo,
			&i.Report.ResolvedBy,
			&i.Report.CreatedAt,
			&i.Report.ResolvedAt,
			&i.TargetIsE2e,
			&i.TargetDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildReportsByStatus = `-- name: ListGuildReportsByStatus :many
SELECT
  r.id, r.reporter_id, r.target_type, r.target_id, r.guild_id, r.reason_category, r.detail, r.status, r.routed_to, r.resolved_by, r.created_at, r.resolved_at,
  m.is_e2e AS target_is_e2e,
  m.deleted_at AS target_deleted_at
FROM reports r
LEFT JOIN messages m ON m.id = r.target_id AND r.target_type = 0
WHERE r.guild_id = $1
  AND r.status = $2
  AND r.id < COALESCE($4::bigint, 9223372036854775807)
ORDER BY r.id DESC
LIMIT $3
`

type ListGuildReportsByStatusParams struct {
	GuildID *int64
	Status  int16
	Limit   int32
	Before  *int64
}

type ListGuildReportsByStatusRow struct {
	Report          Report
	TargetIsE2e     *bool
	TargetDeletedAt pgtype.Timestamptz
}

// One page of a guild's triage queue, filtered to a status.
//
// # The listing carries no content, and that is a decision rather than an omission
//
// It returns the report and two facts *about* the target — whether it is encrypted, and whether it has
// been deleted — so a queue can badge a row without disclosing anything. The reported text lives behind
// [GetGuildReport] alone.
//
// Three reasons, in the order they matter. It gives rule 13's exclusion exactly one place to be right
// instead of two, which is the M15 lesson about a bound enforced twice measuring two different things.
// It bounds the page: fifty reports carrying a 4,000-character message each is a 200 kB response on a
// surface somebody refreshes, which is rule 21 as much as §15. And no screen requires it — `6c` shows an
// excerpt in its table and `6c` is M74's instance queue, not this one.
//
// The earlier draft returned `left(content, $n)` here. Besides the above it would not type: an expression
// through a LEFT JOIN defeats sqlc's nullability inference, so the column came back as a non-nullable
// `string` that a missing target would fail to scan into at runtime.
//
// # Two queries rather than one with an optional filter
//
// The obvious shape is a single query with `status = $n OR $n IS NULL`. M14 measured the OR form on the
// audit log's cursor and it cannot become an index qual under a generic plan — and it recorded that
// COALESCE, which fixes that for a *range* bound, buys nothing for an equality filter, because the
// rewrite names the column on both sides. So an optional equality has no single-query answer that keeps
// the plan.
//
// 000021's measurement makes the split the honest one anyway: the two cases do not want the same plan.
// Filtered to a status the index serves the equality and the ordering together (0.101 ms, 21 buffers);
// unfiltered it falls to a bitmap heap scan and a quicksort (0.409 ms, 109 buffers), which is fine and is
// a different plan. One query that pretended otherwise would get the worse of the two for both.
//
// # The cursor
//
// `before` on the id, newest-first, the COALESCE spelling M14 measured at 9 buffers against 1,859 for the
// OR form. An id rather than created_at: a snowflake is time-ordered *and* unique, while nothing
// constrains created_at, so a page boundary inside a group of equal timestamps would skip or repeat a row.
//
// # The join
//
// LEFT, so a report whose target no longer resolves still appears — a moderator must be able to dismiss a
// report about something that is gone. It does **not** filter `deleted_at`: 000020 says the moderation
// surface reads deleted messages on purpose, and this is that surface.
func (q *Queries) ListGuildReportsByStatus(ctx context.Context, arg ListGuildReportsByStatusParams) ([]ListGuildReportsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listGuildReportsByStatus,
		arg.GuildID,
		arg.Status,
		arg.Limit,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildReportsByStatusRow{}
	for rows.Next() {
		var i ListGuildReportsByStatusRow
		if err := rows.Scan(
			&i.Report.ID,
			&i.Report.ReporterID,
			&i.Report.TargetType,
			&i.Report.TargetID,
			&i.Report.GuildID,
			&i.Report.ReasonCategory,
			&i.Report.Detail,
			&i.Report.Status,
			&i.Report.RoutedTo,
			&i.Report.ResolvedBy,
			&i.Report.CreatedAt,
			&i.Report.ResolvedAt,
			&i.TargetIsE2e,
			&i.TargetDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :one
UPDATE reports
SET status = $3, resolved_at = now(), resolved_by = $4
WHERE id = $1 AND guild_id = $2 AND status = 0
RETURNING id, reporter_id, target_type, target_id, guild_id, reason_category, detail, status, routed_to, resolved_by, created_at, resolved_at
`

type ResolveReportParams struct {
	ID         int64
	GuildID    *int64
	Status     int16
	ResolvedBy *int64
}

// Close a report, with every guard in the statement.
//
// `status = 0` is the terminal-state guard: resolved and dismissed are terminal, so a second close finds
// no row and the service answers 409. Written here rather than as a read-then-write for the reason M10's
// invite redemption was rewritten this way — as a check-then-update, four of four concurrent racers got
// in. `guild_id` is in the WHERE for the cross-scope reason GetGuildReport states.
func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, resolveReport,
		arg.ID,
		arg.GuildID,
		arg.Status,
		arg.ResolvedBy,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.GuildID,
		&i.ReasonCategory,
		&i.Detail,
		&i.Status,
		&i.RoutedTo,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
