// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveSessionsForDevice = `-- name: CountLiveSessionsForDevice :one
SELECT count(*) FROM sessions
WHERE user_id = $1 AND device_id = $2 AND revoked_at IS NULL AND expires_at > now()
`

type CountLiveSessionsForDeviceParams struct {
	UserID   int64
	DeviceID string
}

func (q *Queries) CountLiveSessionsForDevice(ctx context.Context, arg CountLiveSessionsForDeviceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveSessionsForDevice, arg.UserID, arg.DeviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, device_id, refresh_token_hash, device_name, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, device_id, refresh_token_hash, device_name, ip_address, created_at, last_used_at, expires_at, revoked_at, replaced_by_id
`

type CreateSessionParams struct {
	ID               int64
	UserID           int64
	DeviceID         string
	RefreshTokenHash []byte
	DeviceName       *string
	IpAddress        *netip.Addr
	ExpiresAt        pgtype.Timestamptz
}

// Refresh-session queries.
//
// A session is one device's refresh-token family. Rotation replaces a row with a successor and links the
// two; reuse detection walks that link. Every one of these queries is scoped by user_id AND device_id
// wherever it revokes, because revoking across devices is precisely the bug this schema exists to prevent
// (docs/architecture.md §2, ADR 0011).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.RefreshTokenHash,
		arg.DeviceName,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, device_id, refresh_token_hash, device_name, ip_address, created_at, last_used_at, expires_at, revoked_at, replaced_by_id FROM sessions
WHERE refresh_token_hash = $1
`

// The hot path: every refresh looks a session up by hash. Deliberately returns revoked and rotated rows
// too — the caller must be able to tell "no such token" from "a token that was already used", since only
// the second is a replay worth revoking a family over.
func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, device_id, refresh_token_hash, device_name, ip_address, created_at, last_used_at, expires_at, revoked_at, replaced_by_id
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const revokeSessionsForDevice = `-- name: RevokeSessionsForDevice :execrows
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND device_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsForDeviceParams struct {
	UserID   int64
	DeviceID string
}

// Reuse detection: revoke every live session in one device's family. Scoped by device_id as well as
// user_id so another machine's family is untouched — a user with daemons on two computers must not be
// logged out of one because the other replayed a token.
func (q *Queries) RevokeSessionsForDevice(ctx context.Context, arg RevokeSessionsForDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForDevice, arg.UserID, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET revoked_at = now(), replaced_by_id = $2, last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, device_id, refresh_token_hash, device_name, ip_address, created_at, last_used_at, expires_at, revoked_at, replaced_by_id
`

type RotateSessionParams struct {
	ID           int64
	ReplacedByID *int64
}

// Marks a session as replaced by its successor. Revoking at the same moment is what makes the old token
// single-use: a second presentation finds revoked_at set and replaced_by_id populated, which is the replay
// signature.
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.ReplacedByID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByID,
	)
	return i, err
}
