// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyMessageTag = `-- name: ApplyMessageTag :execrows
INSERT INTO message_tag_applications (tag_id, message_id, applied_by)
SELECT t.id, m.id, $1::bigint
FROM message_tags t
JOIN messages m ON m.id = $2::bigint AND m.deleted_at IS NULL
JOIN channels c ON c.id = m.channel_id AND c.guild_id = t.guild_id
WHERE t.id = $3::bigint
ON CONFLICT (tag_id, message_id) DO NOTHING
`

type ApplyMessageTagParams struct {
	AppliedBy int64
	MessageID int64
	TagID     int64
}

// Apply a tag to a message, refusing a pair that crosses a guild boundary.
//
// # The cross-guild predicate is the whole point of the statement's shape
//
// A tag knows its guild; a message reaches one only through channels. So `c.guild_id = t.guild_id` is what
// stops guild A's tag landing on guild B's message — written here rather than checked in Go, because a
// guard in the statement cannot be skipped by the next writer and cannot race. That is the answer M16b's
// security review arrived at for the recording log, and the shape M16 needed when `reports` had no
// guild_id at all.
//
// It is not defence against a confused client. Both ids come from an authorized request, and the service
// checks the caller may see the message and may use the tag. It is defence against the *next* writer —
// a bulk importer, an automation path (M22), a webhook (M60) — which will not be holding the authorize
// result this one does.
//
// `deleted_at IS NULL` refuses a tag on a soft-deleted message: the moderation surfaces read deleted
// messages on purpose (000020), but adding a *new* fact to something already removed is a different act,
// and a tag applied after deletion would surface a deleted message in a tag listing.
//
// ON CONFLICT DO NOTHING makes applying twice idempotent rather than an error, which is what a client
// retrying a request wants. The service distinguishes "already applied" from "refused" by the row count.
func (q *Queries) ApplyMessageTag(ctx context.Context, arg ApplyMessageTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyMessageTag, arg.AppliedBy, arg.MessageID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGuildSharedTags = `-- name: CountGuildSharedTags :one
SELECT count(*) FROM message_tags WHERE guild_id = $1 AND is_shared
`

func (q *Queries) CountGuildSharedTags(ctx context.Context, guildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildSharedTags, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemberPrivateTags = `-- name: CountMemberPrivateTags :one
SELECT count(*) FROM message_tags WHERE guild_id = $1 AND created_by = $2 AND NOT is_shared
`

type CountMemberPrivateTagsParams struct {
	GuildID   int64
	CreatedBy int64
}

func (q *Queries) CountMemberPrivateTags(ctx context.Context, arg CountMemberPrivateTagsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberPrivateTags, arg.GuildID, arg.CreatedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessageTag = `-- name: CreateMessageTag :one

INSERT INTO message_tags (id, guild_id, name, created_by, is_shared)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guild_id, name, created_by, is_shared, created_at
`

type CreateMessageTagParams struct {
	ID        int64
	GuildID   int64
	Name      string
	CreatedBy int64
	IsShared  bool
}

// Message tags (Milestone M17).
// The uniqueness guards are the two partial indexes in 000024, not a check here: a read-then-insert races
// under READ COMMITTED the way M10's invite redemption did, where four of four concurrent racers got in.
// A collision arrives as a unique violation and the service maps it.
func (q *Queries) CreateMessageTag(ctx context.Context, arg CreateMessageTagParams) (MessageTag, error) {
	row := q.db.QueryRow(ctx, createMessageTag,
		arg.ID,
		arg.GuildID,
		arg.Name,
		arg.CreatedBy,
		arg.IsShared,
	)
	var i MessageTag
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.CreatedBy,
		&i.IsShared,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageTag = `-- name: DeleteMessageTag :execrows
DELETE FROM message_tags WHERE id = $1 AND guild_id = $2
`

type DeleteMessageTagParams struct {
	ID      int64
	GuildID int64
}

// Applications cascade with it (000024). The authority check is the service's; this is scoped by guild as
// well as id so a tag id from another guild is not reachable through this guild's path — M15's
// loadInChannel discipline, one object over.
func (q *Queries) DeleteMessageTag(ctx context.Context, arg DeleteMessageTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessageTag, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessageTag = `-- name: GetMessageTag :one
SELECT id, guild_id, name, created_by, is_shared, created_at FROM message_tags WHERE id = $1
`

func (q *Queries) GetMessageTag(ctx context.Context, id int64) (MessageTag, error) {
	row := q.db.QueryRow(ctx, getMessageTag, id)
	var i MessageTag
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.CreatedBy,
		&i.IsShared,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageTagApplication = `-- name: GetMessageTagApplication :one
SELECT tag_id, message_id, applied_by, applied_at FROM message_tag_applications WHERE tag_id = $1 AND message_id = $2
`

type GetMessageTagApplicationParams struct {
	TagID     int64
	MessageID int64
}

// Reads one application by its primary key. Two callers want it for different reasons: Unapply needs
// `applied_by` to decide authority, and Apply uses its presence to tell "already applied" from "refused",
// which the insert's row count cannot distinguish because ON CONFLICT DO NOTHING also reports zero.
func (q *Queries) GetMessageTagApplication(ctx context.Context, arg GetMessageTagApplicationParams) (MessageTagApplication, error) {
	row := q.db.QueryRow(ctx, getMessageTagApplication, arg.TagID, arg.MessageID)
	var i MessageTagApplication
	err := row.Scan(
		&i.TagID,
		&i.MessageID,
		&i.AppliedBy,
		&i.AppliedAt,
	)
	return i, err
}

const listGuildMessageTags = `-- name: ListGuildMessageTags :many
SELECT id, guild_id, name, created_by, is_shared, created_at FROM message_tags
WHERE guild_id = $1 AND (is_shared OR created_by = $2)
ORDER BY id DESC
`

type ListGuildMessageTagsParams struct {
	GuildID   int64
	CreatedBy int64
}

// One guild's tags: every shared one, plus the caller's own private ones.
//
// **The visibility filter is what makes "private" mean anything**, and it is in the SQL rather than in a
// Go loop for the reason rule 13's exclusion is: the next reader of this table inherits it instead of
// having to remember it. A private tag is its creator's alone — not the guild's, not a moderator's — so
// the predicate is `is_shared OR created_by = $2` and there is deliberately no variant without it.
//
// Served by the two partial unique indexes bitmap-OR'd together rather than by a guild_id index, which
// 000024 measured as unnecessary and slightly worse. Bounded at creation rather than paginated (M12's
// rule): `tags.Service` caps a guild's shared tags and each member's private ones, so this list has a
// ceiling and does not need a cursor.
func (q *Queries) ListGuildMessageTags(ctx context.Context, arg ListGuildMessageTagsParams) ([]MessageTag, error) {
	rows, err := q.db.Query(ctx, listGuildMessageTags, arg.GuildID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageTag{}
	for rows.Next() {
		var i MessageTag
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.CreatedBy,
			&i.IsShared,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForMessages = `-- name: ListTagsForMessages :many
SELECT a.message_id, t.id, t.guild_id, t.name, t.created_by, t.is_shared, t.created_at, a.applied_by, a.applied_at
FROM message_tag_applications a
JOIN message_tags t ON t.id = a.tag_id
WHERE a.message_id = ANY($1::bigint[])
  AND (t.is_shared OR t.created_by = $2::bigint)
ORDER BY a.message_id DESC, t.id
`

type ListTagsForMessagesParams struct {
	MessageIds []int64
	ViewerID   int64
}

type ListTagsForMessagesRow struct {
	MessageID  int64
	MessageTag MessageTag
	AppliedBy  int64
	AppliedAt  pgtype.Timestamptz
}

// Every tag on each of a set of messages, with the caller's visibility filter applied.
//
// **One statement for a whole page, never one per message.** Fifty messages resolved one at a time is
// §15.2's N+1 on the path every client hits to draw a channel; `= ANY($1)` is one round trip whatever the
// page size. 000024 measures the index this leans on at 245 buffers against 837, and 2.1 ms against
// 10.5 ms, because without it the scan is over every application on the instance rather than over the
// page.
//
// The same `is_shared OR created_by` filter as the listing, for the same reason: somebody else's private
// tag must not appear on a message you can read, or "private" describes only who may apply it.
func (q *Queries) ListTagsForMessages(ctx context.Context, arg ListTagsForMessagesParams) ([]ListTagsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listTagsForMessages, arg.MessageIds, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForMessagesRow{}
	for rows.Next() {
		var i ListTagsForMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.MessageTag.ID,
			&i.MessageTag.GuildID,
			&i.MessageTag.Name,
			&i.MessageTag.CreatedBy,
			&i.MessageTag.IsShared,
			&i.MessageTag.CreatedAt,
			&i.AppliedBy,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unapplyMessageTag = `-- name: UnapplyMessageTag :execrows
DELETE FROM message_tag_applications WHERE tag_id = $1 AND message_id = $2
`

type UnapplyMessageTagParams struct {
	TagID     int64
	MessageID int64
}

// No guild predicate needed: the pair is the primary key, and a pair that crosses a guild could never have
// been written by the statement above. The authority check is the service's.
func (q *Queries) UnapplyMessageTag(ctx context.Context, arg UnapplyMessageTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, unapplyMessageTag, arg.TagID, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
