// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_factor.sql

package db

import (
	"context"
)

const confirmTOTP = `-- name: ConfirmTOTP :one
UPDATE user_totp
SET confirmed_at = now()
WHERE user_id = $1 AND confirmed_at IS NULL
RETURNING user_id, secret_encrypted, confirmed_at, created_at
`

// The moment the factor becomes required. Guarded on still being unconfirmed so a replayed confirmation
// cannot move the timestamp, which is the same single-transition discipline the device flow uses.
func (q *Queries) ConfirmTOTP(ctx context.Context, userID int64) (UserTotp, error) {
	row := q.db.QueryRow(ctx, confirmTOTP, userID)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE user_recovery_codes
SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
RETURNING id, user_id, code_hash, used_at, created_at
`

type ConsumeRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

// Spend one code, exactly once.
//
// Every guard is in the WHERE: the code must belong to this account, and must not already be spent. Two
// requests presenting the same code both reach this statement and Postgres serializes them on the row, so
// the second re-evaluates `used_at IS NULL` against the first's committed value and matches nothing. A
// read-then-update in Go would let both through, which is the shape RedeemInstanceInvite was rewritten out
// of at M10 after four of four concurrent racers got in.
//
// Scoped by user_id as well as the hash even though the hash is unique, for the reason every revoking
// query in sessions.sql is scoped by device: a lookup that can only ever match this account's rows cannot
// be made to act on another's by a collision or a future schema change.
func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (UserRecoveryCode, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	var i UserRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countLiveRecoveryCodes = `-- name: CountLiveRecoveryCodes :one
SELECT count(*) FROM user_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

// Served by user_recovery_codes_live_idx (000014). Read by the profile response and by the regenerate
// path, so it scales with the codes an account has left rather than with every set it has ever had.
func (q *Queries) CountLiveRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO user_recovery_codes (id, user_id, code_hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, used_at, created_at
`

type CreateRecoveryCodeParams struct {
	ID       int64
	UserID   int64
	CodeHash []byte
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (UserRecoveryCode, error) {
	row := q.db.QueryRow(ctx, createRecoveryCode, arg.ID, arg.UserID, arg.CodeHash)
	var i UserRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecoveryCodesForUser = `-- name: DeleteRecoveryCodesForUser :execrows
DELETE FROM user_recovery_codes WHERE user_id = $1
`

// Used when the whole set is replaced or the factor is disabled. Deletes rather than marking spent: these
// are not evidence of anything once the factor they belonged to is gone.
func (q *Queries) DeleteRecoveryCodesForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecoveryCodesForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTOTPForUser = `-- name: DeleteTOTPForUser :execrows
DELETE FROM user_totp WHERE user_id = $1
`

func (q *Queries) DeleteTOTPForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTOTPForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTOTPForUser = `-- name: GetTOTPForUser :one
SELECT user_id, secret_encrypted, confirmed_at, created_at FROM user_totp WHERE user_id = $1
`

// Deliberately returns unconfirmed rows. "Is a factor owed" and "is an enrollment in progress" are
// different questions and the caller asks both; a query that hid unconfirmed rows would make the second
// unanswerable and silently let a second enrollment overwrite one in flight.
func (q *Queries) GetTOTPForUser(ctx context.Context, userID int64) (UserTotp, error) {
	row := q.db.QueryRow(ctx, getTOTPForUser, userID)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTOTPEnrollment = `-- name: UpsertTOTPEnrollment :one

INSERT INTO user_totp (user_id, secret_encrypted)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET secret_encrypted = EXCLUDED.secret_encrypted, confirmed_at = NULL, created_at = now()
RETURNING user_id, secret_encrypted, confirmed_at, created_at
`

type UpsertTOTPEnrollmentParams struct {
	UserID          int64
	SecretEncrypted []byte
}

// Second-factor queries: one TOTP enrollment per account, and its recovery codes.
//
// Single-use lives in the statement here as it does everywhere else in this package — see
// ConsumeRecoveryCode below, and password_reset_tokens.sql for the reasoning it shares.
// Begin (or restart) enrollment. Unconfirmed until a code proves the authenticator works.
//
// ON CONFLICT replaces rather than refusing, because the case it serves is somebody who lost the QR code
// half-way and started again. Confirming is what makes a factor real, so replacing an *unconfirmed* row
// costs nothing — and replacing a confirmed one is prevented by the caller, which requires the current
// factor before it will touch an account that already has one.
func (q *Queries) UpsertTOTPEnrollment(ctx context.Context, arg UpsertTOTPEnrollmentParams) (UserTotp, error) {
	row := q.db.QueryRow(ctx, upsertTOTPEnrollment, arg.UserID, arg.SecretEncrypted)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}
