// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, email, password_hash, display_name, email_verified_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, password_hash, display_name, avatar_hash, email_verified_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID              int64
	Username        string
	Email           string
	PasswordHash    *string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
}

// Account queries.
//
// Every read filters `deleted_at IS NULL`: a soft-deleted account keeps its row so authored content can
// still render as "Deleted User", but it must never be findable for login, registration collision, or
// profile lookup. Leaving that filter off is the way a deleted account quietly becomes usable again.
// email_verified_at is a parameter rather than a default, because the three callers disagree about it and
// each is right.
//
// Registration passes NULL: the address is a claim until somebody follows a link sent to it. Bootstrap
// passes now(), because the operator proved filesystem access to the instance's own config, which is
// strictly more than an emailed link proves — asking them to check their mail to finish setting up a
// server they are holding the keys to would be theatre, and would make bootstrap impossible on an
// instance with no relay. The OAuth path has its own insert (CreateOAuthUser) because it creates an
// account with no password at all.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, avatar_hash, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, display_name, avatar_hash, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const reserveUsername = `-- name: ReserveUsername :exec
INSERT INTO registration_reservations (username)
VALUES ($1)
ON CONFLICT (username) DO NOTHING
`

// Claims a username for a registration that created no account.
//
// ON CONFLICT DO NOTHING because the name may already be claimed by an account or by an earlier
// reservation, and either way the caller's answer is the same: it is not available. Nothing here needs to
// know which.
func (q *Queries) ReserveUsername(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, reserveUsername, username)
	return err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE email = $1 AND deleted_at IS NULL
) AS taken
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const usernameUnavailable = `-- name: UsernameUnavailable :one
SELECT EXISTS (
  SELECT 1 FROM users u WHERE u.username = $1 AND u.deleted_at IS NULL
  UNION ALL
  SELECT 1 FROM registration_reservations r WHERE r.username = $1
) AS unavailable
`

// Is this username claimed, by an account or by a registration that created none?
//
// The second half is what closes the last leg of the registration oracle, and it is not optional: a
// registration against a *taken* address creates no account, so without a reservation it would leave the
// username free while one against a fresh address does not — and two requests read that difference. See
// migration 000011.
//
// One query rather than two so the two halves cannot be checked in different places, or one of them
// forgotten by a later caller.
func (q *Queries) UsernameUnavailable(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameUnavailable, username)
	var unavailable bool
	err := row.Scan(&unavailable)
	return unavailable, err
}
